api_reportpointofsaleandproduct_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.api.controller.reportpointofsaleandproduct:indexAction
        _tianos:
            section: admin
            permission: true
            grid: sylius_admin_reportpointofsaleandproduct
            template: ReportpointofsaleandproductBundle:Reportpointofsaleandproduct:index.html.twig
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                icon: cube
            form:
                type: Bundle\ReportpointofsaleandproductBundle\Form\Type\ReportpointofsaleandproductType
            repository:
                service: tianos.repository.reportpointofsaleandproduct
                method: findAll
                arguments: [$reportpointofsaleandproductId]
