api_report_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.api.controller.report:indexAction
        _tianos:
            section: admin
            permission: true
            grid: sylius_admin_report
            template: ReportBundle:Report:index.html.twig
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                icon: cube
            form:
                type: Bundle\ReportBundle\Form\Type\ReportType
            repository:
                service: tianos.repository.report
                method: findAll
                arguments: [$reportId]
