Bundle\VisitBundle\Entity\Visit:
    type: entity
    table: visit
    repositoryClass: Bundle\VisitBundle\Doctrine\ORM\VisitRepository
    indexes:
        fk_visita_user1_idx:
            columns:
                - user_id
        fk_visita_point_of_sale1_idx:
            columns:
                - point_of_sale_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        visitStart:
            type: datetime
            nullable: true
            column: visit_start
        visitEnd:
            type: datetime
            nullable: true
            column: visit_end
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        userCreate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        userUpdate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_update
        isActive:
            type: boolean
            nullable: false
            column: is_active
        uuid:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    manyToOne:
        pointOfSale:
            targetEntity: Bundle\PointofsaleBundle\Entity\Pointofsale
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                point_of_sale_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Bundle\UserBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
