api_default:
    resource: '@ApiBundle/Resources/config/routing/default.yml'
    prefix: /

api_pointofsale:
    resource: '@PointofsaleBundle/Resources/config/routing/api.yml'
    prefix: /point-of-sale

api_user:
    resource: '@UserBundle/Resources/config/routing/api.yml'
    prefix: /user