backend_profile_has_role_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.profilehasrole.controller.profile:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: OneToManyBundle::index.html.twig
            vars:
                subheader: sylius.ui.manage_your_profile_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
            one_to_many:
                box:
                    icon: exchange
                    class: primary
                    form_name: main-form
                    title: Profile has Role
                box_left:
                    icon: user-secret
                    class: primary
                    id: box-left-id
                    title: Profile
                    li_id: box-left-li
                    li_badge_class: bg-blue
                    li_input_name: box-lefts-selected-value
                    search_input_name: search-input-name-left
                    route_search: backend_profile_has_role_boxleft_search
                box_right:
                    icon: expeditedssl
                    class: primary
                    id: box-right-id
                    title: Role
                    li_id: box-right-li
                    li_badge_class: bg-orange-active
                    li_input_name: box-right-selected-value
                    search_input_name: search-input-name-right
                    route_search: backend_profile_has_role_boxright_search
            form:
                type: Bundle\ProfileBundle\Form\Type\ProfileType
            repository:
                box_left:
                    service: tianos.repository.profile
                    method: findAllOffsetLimit
                    arguments:
                        limit: 20
                box_right:
                    service: tianos.repository.role
                    method: findAllOffsetLimit
                    arguments:
                        limit: 20

backend_profile_has_role_boxleft_search:
    path: /box-left-search
    methods: [POST]
    defaults:
        _controller: tianos.profilehasrole.controller.profile:boxLeftSearchAction
        _tianos:
            action: left_search
            template: OneToManyBundle:Li:box_left.html.twig
            vars:
                serialize_group_name: crud
            one_to_many:
                box_left:
#                    icon: user-secret
#                    class: primary
#                    id: box-left-id
#                    title: Profile
                    li_id: box-left-li
                    li_badge_class: bg-blue
                    li_input_name: box-lefts-selected-value
                    search_input_name: search-input-name-left
#                    route_search: backend_profile_has_role_boxleft_search
            repository:
                box_left:
                    service: tianos.repository.profile
                    method: searchBoxLeft
                    arguments:
                        limit: 20
#            entity: Bundle\ProfileBundle\Entity\Profile
#            form:
#                type: Bundle\ProfileBundle\Form\Type\ProfileType

backend_profile_has_role_boxright_search:
    path: /box-right-search
    methods: [POST]
    defaults:
        _controller: tianos.profilehasrole.controller.profile:boxRightSearchAction
        _tianos:
            action: right_search
            template: OneToManyBundle:Li:box_right.html.twig
            vars:
                serialize_group_name: crud
            one_to_many:
                box_right:
#                    icon: user-secret
#                    class: primary
#                    id: box-right-id
#                    title: Profile
                    li_id: box-right-li
                    li_badge_class: bg-blue
                    li_input_name: box-lefts-selected-value
                    search_input_name: search-input-name-left
#                    route_search: backend_profile_has_role_boxleft_search
            repository:
                box_right:
                    service: tianos.repository.role
                    method: searchBoxRight
                    arguments:
                        limit: 20
#            entity: Bundle\ProfileBundle\Entity\Profile
#            form:
#                type: Bundle\ProfileBundle\Form\Type\ProfileType







backend_profile_has_role_edit:
    path: /edit
    methods: [PUT, POST]
    defaults:
        _controller: tianos.profilehasrole.controller.profile:editAction
        _tianos:
            action: edit
            template: ProfileBundle:ProfileBackend/Form:form.html.twig
            repository:
                service: tianos.repository.profile
                method: find
                arguments: [$profileId]
            form:
                type: Bundle\ProfileBundle\Form\Type\ProfileType
            vars:
                serialize_group_name: crud

backend_profile_has_role_delete:
    path: /delete
    methods: [POST, DELETE]
    defaults:
        _controller: tianos.profilehasrole.controller.profile:deleteAction
        _tianos:
            action: delete
            template: GridBundle:Template:delete.html.twig
            repository:
                service: tianos.repository.profile
                method: find
                arguments: [$profileId]
            vars:
#                body_css: grid-body-css

backend_profile_has_role_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.profilehasrole.controller.profile:viewAction
        _tianos:
            action: view
            template: ProfileBundle:ProfileBackend/Informative:view.html.twig
            repository:
                service: tianos.repository.profile
                method: find
                arguments: [$profileId]

backend_profile_has_role_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.profilehasrole.controller.profile:infoAction
        _tianos:
            action: info
            template: ProfileBundle:ProfileBackend/Informative:info.html.twig
