---

- hosts: webservers
  vars:
    - welcomeMsg: "Pollo gordo 33333333333"

  tasks:
    - name: SetUp Python
      apt: pkg=python state=installed update_cache=true
    - name: SetUp Php 7.0
      apt: pkg=php7.0-cli state=installed update_cache=true
    - name: SetUp Nginx
      apt: pkg=nginx state=installed update_cache=true
    - name: SetUp Phpunit
      apt: pkg=phpunit state=installed update_cache=true
#    - name: Copy Index.html files
#      template: src=index.html dest=/var/www/html/index.html

#apt-get install php7.0-cli

#    - name: Setting up Security/Firewall Group
#    ec2_group:
#      name: AWS_Security_Grp
#      description: Rules Allowing Traffic on port 22 and 80
#      region: us-west-2
#      rules:
#        - proto: tcp
#          from_port: 80
#          to_port: 80
#          cidr_ip: 0.0.0.0/0
#        - proto: tcp
#          from_port: 22
#          to_port: 22
#          cidr_ip: 0.0.0.0/0
#      rules_egress:
#        - proto: all
#          cidr_ip: 0.0.0.0/0