Component\CRUD_DUMMY\Model\CRUD_DUMMYOptionValueTranslation:
    exclusion_policy: ALL
    xml_root_name: option-value
    properties:
        id:
            expose: true
            groups: [Default, Detailed, DetailedCart]
        locale:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
        value:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
