services:

    tianos.listener.doctrine.user:
        class: Bundle\UserBundle\EventListener\DoctrineListenerService
        arguments: ["@security.token_storage", "@security.password_encoder"]
        tags:
          - { name: doctrine.event_listener, event: postUpdate }
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: postLoad }
          - { name: doctrine.event_listener, event: postRemove }

    tianos.api.controller.user:
        class: Bundle\UserBundle\Controller\ApiController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.api.controller.user, alias: tianos.api.controller.user }

    tianos.backend.controller.user:
        class: Bundle\UserBundle\Controller\BackendController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.backend.controller.user, alias: tianos.backend.controller.user }

    tianos.backend.setting.controller.user:
        class: Bundle\UserBundle\Controller\BackendSettingController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.backend.setting.controller.user, alias: tianos.backend.setting.controller.user }

    tianos.frontend.controller.user:
        class: Bundle\UserBundle\Controller\FrontendController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.frontend.controller.user, alias: tianos.frontend.controller.user }

    tianos.security.controller.user:
        class: Bundle\UserBundle\Controller\SecurityController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        public: true
        tags:
            - { name: tianos.security.controller.user, alias: tianos.security.controller.user }

    tianos.repository.user:
        class: Dummy
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Bundle\UserBundle\Entity\User ]

#    tianos.form.type.user.register:
#        class: Bundle\UserBundle\Form\Type\UserRegisterType
#        arguments: [ '%application_url%' ]
#        tags:
#            - { name: tianos.form.type.user.register, alias: tianos.form.type.user.register }

