Bundle\ProductBundle\Entity\Unit:
    type: entity
    table: unit
    repositoryClass: Bundle\ProductBundle\Doctrine\ORM\UnitRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        isActive:
            type: boolean
            nullable: true
            column: is_active
    lifecycleCallbacks: {  }
