#backend_product_index:
#    path: /
#    defaults: { _controller: ProductBundle:Product:index }
#    methods: [GET]


product_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.controller.product:indexAction
        _sylius:
            section: admin
            permission: true
            grid: sylius_admin_product
            template: ProductBundle:Product:index.html.twig
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                icon: cube
            form:
                type: Bundle\ProductBundle\Form\Type\ProductType
            repository:
                method: findAll
                arguments: [$productId]




#            template: "@SyliusAdmin/ProductVariant/generate.html.twig"
#            section: admin
#            permission: true
#            redirect:
#                route: sylius_admin_product_variant_index
#                parameters: { productId: $productId }
#            form:
#                type: Sylius\Bundle\ProductBundle\Form\Type\ProductGenerateVariantsType
#            repository:
#                method: find
#                arguments: [$productId]
#            flash: sylius.product_variant.generate



#
#sylius_admin_product_index:
#    path: /products/
#    methods: [GET]
#    defaults:
#        _controller: sylius.controller.product:indexAction
#        _sylius:
#            section: admin
#            permission: true
#            grid: sylius_admin_product
#            template: SyliusAdminBundle:Product:index.html.twig
#            vars:
#                subheader: sylius.ui.manage_your_product_catalog
#                icon: cube


#backend_product_create:
#    path: /create
#    defaults: { _controller: 'BackendBundle:Product:create' }
#    methods: [POST]
#
#backend_product_edit:
#    path: /edit
#    defaults: { _controller: 'BackendBundle:Product:edit' }
#    methods: [POST, PUT]
#
#backend_product_delete:
#    path: /delete
#    defaults: { _controller: 'BackendBundle:Product:delete' }
#    methods: [POST, DELETE]
#
#backend_product_view:
#    path: /view
#    defaults: { _controller: 'BackendBundle:Product:view' }
#    methods: [POST]
#
#backend_product_info:
#    path: /info
#    defaults: { _controller: 'BackendBundle:Product:info' }
#    methods: [POST]
