services:

    tianos.controller.product:
        class: Bundle\ProductBundle\Controller\ProductController
        arguments: [ Bundle\GridBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.controller.product, alias: tianos.controller.product }

#    tianos.controller.grid:
#        class: Bundle\GridBundle\Controller\GridController
#        arguments: [ Bundle\GridBundle\Controller\RequestConfigurationFactoryInterface ]
#        tags:
#            - { name: tianos.controller.grid, alias: tianos.controller.grid }

    tianos.repository.product:
        class: Dummy
#        class: Bundle\ProductBundle\Doctrine\ORM\ProductRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Bundle\ProductBundle\Entity\Product ]
#        arguments: [ Component\Product\Model\Product ]
