backend_profile_user_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.user:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            vars:
                subheader: sylius.ui.manage_your_user_catalog
                icon: cube
                body_css: grid-body-css
            grid:
                icon: user
                box_class: primary
                title: Usuarios del sistema
                modal:
                    title: Crear usuario
                data_table:
                    route:
                        info: backend_profile_user_info
                        view: backend_profile_user_view
#                        edit: backend_profile_user_edit
#                        create: backend_profile_user_create
#                        delete: backend_profile_user_delete
                    table_button:
#                        - edit
#                        - delete
                    table_option:
                        pageLength: 50
                    table_button_header:
#                        - create
                        - info
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
                    columns:
                        - name: '#'
                          obj: " '<span class=\"badge bg-blue\">' + obj.id + '</span>' "
                        - name: Nombre
                          obj: " obj.name + ' ' + obj.last_name "
                        - name: Email
                          obj: obj.email
                          options:
                              icon: envelope-o
                        - name: Username
                          obj: " '<span class=\"badge bg-green\">' + obj.username + '</span>' "
                          options:
                              icon: feed
                        - name: Creado
                          obj: obj.created_at
                          options:
                              icon: calendar
            form:
                type: Bundle\UserBundle\Form\Type\UserType
            repository:
                service: tianos.repository.user
                method: findAll
                arguments: [$userId]
                vars:
                    serialize_group_name: crud

backend_profile_user_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.user:viewAction
        _tianos:
            action: view
            template: UserBundle:UserBackend/Informative:view_anonymous.html.twig
            repository:
                service: tianos.repository.user
                method: find
                arguments: [$userId]
                vars:
                    serialize_group_name: crud

backend_profile_user_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.user:infoAction
        _tianos:
            action: info
            template: UserBundle:UserBackend/Informative:info.html.twig

