backend_setting_user_index:
    path: /{active}
    methods: [POST]
    defaults:
        _controller: tianos.backend.setting.controller.user:indexAction
        _tianos:
            action: view
            template: UserBundle:UserBackend/Informative:view_anonymous.html.twig
            repository:
                service: tianos.repository.user
                method: find
                arguments: [$userId]
                vars:
                    serialize_group_name: crud

backend_setting_user_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.user:infoAction
        _tianos:
            action: info
            template: UserBundle:UserBackend/Informative:info.html.twig

