backend_user_employee_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.user:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            vars:
                subheader: sylius.ui.manage_your_user_catalog
                icon: cube
                body_css: grid-body-css
            grid:
                icon: user
                box_class: primary
                title: Listado de empleados
                modal:
                    title: Crear usuario
                data_table:
                    route:
                        info: backend_user_employee_info
                        view: backend_user_employee_view
                        view_profile: frontend_user_profile
                        edit: backend_user_employee_edit
                        create: backend_user_employee_create
                        delete: backend_user_employee_delete
                    table_button:
                        - view_profile
                        - edit
                        - delete
                    table_option:
                        pageLength: 50
                        dom: "'<\"top\"flp><\"clear\">rt<\"bottom\"flp>'"
                    table_button_header:
                        - create
                        - info
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: data-slug
                          value: aData.slug
                        - key: class
                          value: "'alert'"
                    columns:
                        - name: Nombre
                          obj: " obj.name + ' ' + obj.last_name "
                        - name: Username
                          obj: " '<span class=\"badge bg-green\">' + obj.username + '</span>' "
                          options:
                              icon: feed
                        - name: Usuario desde
                          obj: obj.created_at
                          options:
                              icon: calendar
            form:
                type: Bundle\UserBundle\Form\Type\UserType
            repository:
                service: tianos.repository.user
                method: findAllEmployee
                arguments: [$userId]
                vars:
                    serialize_group_name: crud

backend_user_employee_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.user:createAction
        _tianos:
            action: create
            template: UserBundle:BackendUser/Form:form.html.twig
            entity: Bundle\UserBundle\Entity\User
            form:
                type: Bundle\UserBundle\Form\Type\UserType
            repository:
                vars:
                    serialize_group_name: crud

backend_user_employee_edit:
    path: /edit
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.user:editAction
        _tianos:
            action: edit
            template: UserBundle:BackendUser/Form:form.html.twig
            form:
                type: Bundle\UserBundle\Form\Type\UserType
            repository:
                service: tianos.repository.user
                method: find
                arguments: [$roleId]
                vars:
                    serialize_group_name: crud

backend_user_employee_delete:
    path: /delete
    methods: [POST, DELETE]
    defaults:
        _controller: tianos.backend.controller.user:deleteAction
        _tianos:
            action: delete
            template: GridBundle:Template:delete.html.twig
            repository:
                service: tianos.repository.user
                method: find
                arguments: [$roleId]
            vars:
#                body_css: grid-body-css

backend_user_employee_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.user:viewAction
        _tianos:
            action: view
            template: UserBundle:BackendUser/Informative:view_client.html.twig
            repository:
                service: tianos.repository.user
                method: find
                arguments: [$userId]
                vars:
                    serialize_group_name: crud

backend_user_employee_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.user:infoAction
        _tianos:
            action: info
            template: UserBundle:UserBackend/Informative:info.html.twig

