backend_security_login:
    path: /login
    methods: [GET, POST]
    defaults:
        _controller: tianos.security.controller.user:loginAction
        _tianos:
            action: create
            template: UserBundle:UserBackend/Security:login.html.twig

backend_security_register:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: tianos.security.controller.user:registerAction
        _tianos:
            action: create
            template: UserBundle:UserBackend/Security:register.html.twig

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile