backend_security_login:
    path: /login
    methods: [GET, POST]
    defaults:
        _controller: tianos.security.controller.user:loginAction
        _tianos:
            action: create
            template: UserBundle:BackendUser/Security:login.html.twig

backend_security_login_facebook_callback:
    path: /login-facebook-callback
    methods: [GET, POST]
    defaults:
        _controller: tianos.security.controller.user:loginFacebookCallbackAction
        _tianos:
            action: create
            template: UserBundle:BackendUser/Security:login-facebook.html.twig
            vars:
                subheader: sylius.ui.manage_your_orderin_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
                box:
                    icon: newspaper-o
                    class: primary

backend_security_reset_password_step_one:
    path: /reset-password-step-one
    methods: [GET, POST]
    defaults:
        _controller: tianos.security.controller.user:resetPasswordStepOneAction
        _tianos:
            action: create
            template: UserBundle:BackendUser/Security:reset-password-step-one.html.twig
            vars:
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
                form:
                    type: Bundle\UserBundle\Form\Type\UserForgotPasswordType

backend_security_reset_password_step_two:
    path: /reset-password-step-two
    methods: [GET, POST]
    defaults:
        _controller: tianos.security.controller.user:resetPasswordStepTwoAction
        _tianos:
            action: create
            template: UserBundle:BackendUser/Security:reset-password-step-two.html.twig
            vars:
                icon: cube
                body_css: password-body-css
                serialize_group_name: crud
                form:
                    type: Bundle\UserBundle\Form\Type\UserForgotPasswordType

backend_security_register:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: tianos.security.controller.user:registerAction
        _tianos:
            action: create
            template: UserBundle:BackendUser/Security:register.html.twig

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile