backend_security_login:
    path: /login
    methods: [GET, POST]
    defaults:
        _controller: tianos.security.controller.user:loginAction
        _tianos:
            action: create
            template: UserBundle:UserBackend/Security:login.html.twig
#            entity: Bundle\ProductBundle\Entity\Product
#            form:
#                type: Bundle\ProductBundle\Form\Type\ProductType
#            vars:
#                serialize_group_name: crud

backend_security_check_path:
    path: /login-check
    methods: [GET, POST]
    defaults:
        _controller: tianos.security.controller.user:checkAction
        _tianos:
#            action: create
#            template: UserBundle:UserBackend/Security:login.html.twig
#            entity: Bundle\ProductBundle\Entity\Product
#            form:
#                type: Bundle\ProductBundle\Form\Type\ProductType
#            vars:
#                serialize_group_name: crud


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile