Bundle\ReportpointofsaleandproductBundle\Entity\Reportpointofsaleandproduct:
    type: entity
    table: report_point_of_sale_and_product
    repositoryClass: Bundle\ReportpointofsaleandproductBundle\Doctrine\ORM\ReportpointofsaleandproductRepository
    indexes:
#        fk_report_point_of_sale_and_product_point_of_sale_has_produ_idx:
#            columns:
#                - point_of_sale_has_product_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        timeDelivery:
            type: datetime
            nullable: true
            column: time_delivery
        stockOut:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: stock_out
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        userCreate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        userUpdate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_update
        isActive:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: is_active
#    manyToOne:
#        pointOfSaleHasProduct:
#            targetEntity: PointOfSaleHasProduct
#            cascade: {  }
#            fetch: LAZY
#            mappedBy: null
#            inversedBy: null
#            joinColumns:
#                point_of_sale_has_product_id:
#                    referencedColumnName: id
#            orphanRemoval: false
    lifecycleCallbacks: {  }