<?php

namespace Bundle\CoreBundle\Repository;

/**
 * DefaultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefaultRepository extends \Doctrine\ORM\EntityRepository
{

}
