<?php

namespace Bundle\CoreBundle\Repository;

/**
 * GatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GatoRepository extends \Doctrine\ORM\EntityRepository
{
}
