<?php

namespace Bundle\CoreBundle\Repository;

/**
 * pollo2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pollo2Repository extends \Doctrine\ORM\EntityRepository
{
}
