backend_booking_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.booking:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            vars:
                subheader: sylius.ui.manage_your_booking_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
            grid:
                icon: calendar
                box_class: primary
                title: Gestionar booking
                modal:
                    create:
                        title: Crear booking
                        size: modal-lg
                    edit:
                        title: Editar booking
                        size: modal-lg
                data_table:
                    route:
                        info: backend_booking_info
                        view: backend_booking_view
                        edit: backend_booking_edit
                        create: backend_booking_create
                        delete: backend_booking_delete
                    table_button:
                        - edit
                        - delete
                    table_button_header:
                        - create
                        - info
                    table_option:
                        pageLength: 10
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
                    columns:
                        - name: '#'
                          obj: " '<span class=\"badge bg-blue\">' + obj.id + '</span>' "
                        - name: Nombre
                          obj: obj.name
                        - name: Cliente
                          obj: obj.client.name_box
                          options:
                              icon: user
                        - name: Fecha book
                          obj: obj.date_book
                          options:
                              icon: calendar
                        - name: Hora inicio
                          obj: obj.time_in_book
                          options:
                              icon: clock-o
                        - name: Hora fin
                          obj: obj.time_out_book
                          options:
                              icon: clock-o
            form:
                type: Bundle\BookingBundle\Form\Type\BookingType
            repository:
                service: tianos.repository.booking
                method: findAll
                arguments: [$bookingId]
                vars:
                    serialize_group_name: crud

backend_booking_calendar:
    path: /calendar
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.booking:calendarAction
        _tianos:
            template: BookingBundle:BackendBooking/Calendar:index.html.twig
            vars:
                subheader: sylius.ui.manage_your_booking_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
                calendar: calendar
                route:
                    info: backend_booking_info
                    view: backend_booking_view
                    edit: backend_booking_edit
                    create: backend_booking_create
                    delete: backend_booking_delete
            grid:
                icon: cube
                box_class: primary
                title: Gestionar booking
                modal:
                    create:
                        title: Crear booking
                        size: modal-lg
                    edit:
                        title: Editar booking
                        size: modal-lg

backend_booking_calendar_events:
    path: /calendar-events
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.booking:calendarEventsAction
        _tianos:
#            template: BookingBundle:BackendBooking/Calendar:index.html.twig
            vars:
                subheader: sylius.ui.manage_your_booking_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud

backend_booking_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.booking:createAction
        _tianos:
            action: create
            template: BookingBundle:BackendBooking/Form:form.html.twig
            entity: Bundle\BookingBundle\Entity\Booking
            form:
                type: Bundle\BookingBundle\Form\Type\BookingType
            repository:
                vars:
                    serialize_group_name: crud

backend_booking_edit:
    path: /edit
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.booking:editAction
        _tianos:
            action: edit
            template: BookingBundle:BackendBooking/Form:form.html.twig
            form:
                type: Bundle\BookingBundle\Form\Type\BookingType
            repository:
                service: tianos.repository.booking
                method: find
                arguments: [$bookingId]
                vars:
                    serialize_group_name: crud

backend_booking_delete:
    path: /delete
    methods: [POST, DELETE]
    defaults:
        _controller: tianos.backend.controller.booking:deleteAction
        _tianos:
            action: delete
            template: GridBundle:Template:delete.html.twig
            repository:
                service: tianos.repository.booking
                method: find
                arguments: [$bookingId]
            vars:
#                body_css: grid-body-css

backend_booking_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.booking:viewAction
        _tianos:
            action: view
            template: BookingBundle:BackendBooking/Informative:view.html.twig
            repository:
                service: tianos.repository.booking
                method: find
                arguments: [$bookingId]
                vars:
                    serialize_group_name: crud

backend_booking_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.booking:infoAction
        _tianos:
            action: info
            template: BookingBundle:BackendBooking/Informative:info.html.twig





#/var/www/html/Sylius/sylius/vendor/sylius/sylius/docs/customization/factory.rst
#
#    sylius_admin_product_create_simple:
#        path: /products/new/simple
#        methods: [GET, POST]
#        defaults:
#            _controller: sylius.controller.product:createAction
#            _sylius:
#                section: admin
#                factory:
#                    method: createDisabled # like here for example
#                template: SyliusAdminBundle:Crud:create.html.twig
#                redirect: sylius_admin_product_update
#                vars:
#                    subheader: sylius.ui.manage_your_product_catalog
#                    templates:
#                        form: SyliusAdminBundle:CRUDDUMMY:_form.html.twig
#                    route:
#                        name: sylius_admin_product_create_simple



#            template: "@SyliusAdmin/ProductVariant/generate.html.twig"
#            section: admin
#            permission: true
#            redirect:
#                route: sylius_admin_product_variant_index
#                parameters: { productId: $productId }
#            form:
#                type: Sylius\Bundle\ProductBundle\Form\Type\ProductGenerateVariantsType
#            repository:
#                method: find
#                arguments: [$productId]
#            flash: sylius.product_variant.generate

#sylius_admin_product_index:
#    path: /products/
#    methods: [GET]
#    defaults:
#        _controller: sylius.controller.product:indexAction
#        _sylius:
#            section: admin
#            permission: true
#            grid: sylius_admin_product
#            template: SyliusAdminBundle:CRUDDUMMY:index.html.twig
#            vars:
#                subheader: sylius.ui.manage_your_product_catalog
#                icon: cube
