api_ticket_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.api.controller.ticket:indexAction
        _tianos:
            section: admin
            permission: true
            grid: sylius_admin_ticket
            template: TicketBundle:Ticket:index.html.twig
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                icon: cube
            form:
                type: Bundle\TicketBundle\Form\Type\TicketType
            repository:
                service: tianos.repository.ticket
                method: findAll
                arguments: [$ticketId]
