backend_default:
    resource: '@BackendBundle/Resources/config/routing/default.yml'
    prefix: /

backend_product:
    resource: '@ProductBundle/Resources/config/routing/product-backend.yml'
    prefix: /products








#backend_user:
#    resource: '@BackendBundle/Resources/config/routing/routing/user.yml'
#    prefix: /user
#
#backend_session:
#    resource: '@BackendBundle/Resources/config/routing/session.yml'
#    prefix: /session