backend_default:
    resource: '@BackendBundle/Resources/config/routing/default.yml'
    prefix: /
backend_associative:
    resource: '@AssociativeBundle/Resources/config/routing.yml'
    prefix: /associative
backend_groupofusers:
    resource: '@GroupofusersBundle/Resources/config/routing/backend.yml'
    prefix: /group-of-users
backend_role:
    resource: '@RoleBundle/Resources/config/routing/backend.yml'
    prefix: /role
backend_profile:
    resource: '@ProfileBundle/Resources/config/routing/backend.yml'
    prefix: /profile
backend_security:
    resource: '@UserBundle/Resources/config/routing/security.yml'
    prefix: /security
backend_core:
    resource: '@CoreBundle/Resources/config/routing/backend.yml'
    prefix: /core
backend_session:
    resource: '@SessionBundle/Resources/config/routing/backend.yml'
    prefix: /session
backend_visit:
    resource: '@VisitBundle/Resources/config/routing/backend.yml'
    prefix: /visit
backend_report:
    resource: '@ReportBundle/Resources/config/routing/backend.yml'
    prefix: /report
backend_google_drive:
    resource: '@GoogleBundle/Resources/config/routing/google_drive_file.yml'
    prefix: /google-drive
backend_google_drive_grid:
    resource: '@GoogleBundle/Resources/config/routing/google_drive_file_grid.yml'
    prefix: /google-drive-grid
backend_google_drive_vote:
    resource: '@GoogleBundle/Resources/config/routing/google_drive_file_vote.yml'
    prefix: /google-drive-vote
backend_user:
    resource: '@UserBundle/Resources/config/routing/backend.yml'
    prefix: /user
backend_user_client:
    resource: '@UserBundle/Resources/config/routing/backend_client.yml'
    prefix: /user-client
backend_friends_user:
    resource: '@UserBundle/Resources/config/routing/backend_friends.yml'
    prefix: /user-friends
backend_setting_user:
    resource: '@UserBundle/Resources/config/routing/backend_setting.yml'
    prefix: /user-setting
backend_calendar:
    resource: '@CalendarBundle/Resources/config/routing/backend.yml'
    prefix: /calendar
backend_product:
    resource: '@ProductBundle/Resources/config/routing/backend.yml'
    prefix: /product
backend_pointofsale:
    resource: '@PointofsaleBundle/Resources/config/routing/backend.yml'
    prefix: /point-of-sale