backend_default:
    resource: '@BackendBundle/Resources/config/routing/default.yml'
    prefix: /

backend_product:
    resource: '@ProductBundle/Resources/config/routing/backend-product.yml'
    prefix: /products
