backend_default:
    resource: '@BackendBundle/Resources/config/routing/default.yml'
    prefix: /
backend_associative:
    resource: '@AssociativeBundle/Resources/config/routing.yml'
    prefix: /associative
backend_pointofsale:
    resource: '@PointofsaleBundle/Resources/config/routing/backend.yml'
    prefix: /point-of-sale
backend_pointofsale_map:
    resource: '@PointofsaleBundle/Resources/config/routing/map.yml'
    prefix: /point-of-sale/map
backend_product:
    resource: '@ProductBundle/Resources/config/routing/backend.yml'
    prefix: /product
backend_category:
    resource: '@CategoryBundle/Resources/config/routing/backend.yml'
    prefix: /category
backend_category_tree:
    resource: '@CategoryBundle/Resources/config/routing/tree.yml'
    prefix: /category-tree
backend_groupofusers:
    resource: '@GroupofusersBundle/Resources/config/routing/backend.yml'
    prefix: /group-of-users
backend_client:
    resource: '@ClientBundle/Resources/config/routing/backend.yml'
    prefix: /client
backend_role:
    resource: '@RoleBundle/Resources/config/routing/backend.yml'
    prefix: /role
backend_profile:
    resource: '@ProfileBundle/Resources/config/routing/backend.yml'
    prefix: /profile
backend_user:
    resource: '@UserBundle/Resources/config/routing/backend.yml'
    prefix: /user
backend_security:
    resource: '@UserBundle/Resources/config/routing/security.yml'
    prefix: /security
backend_core:
    resource: '@CoreBundle/Resources/config/routing/backend.yml'
    prefix: /core
backend_session:
    resource: '@SessionBundle/Resources/config/routing/backend.yml'
    prefix: /session
backend_pdvhasproduct:
    resource: '@PdvhasproductBundle/Resources/config/routing/backend.yml'
    prefix: /report-pointofsale-and-product
backend_visit:
    resource: '@VisitBundle/Resources/config/routing/backend.yml'
    prefix: /visit
backend_route:
    resource: '@RouteBundle/Resources/config/routing/backend.yml'
    prefix: /route
backend_orderin:
    resource: '@OrderBundle/Resources/config/routing/backend_in.yml'
    prefix: /order/in
backend_order_report:
    resource: '@OrderBundle/Resources/config/routing/backend_report.yml'
    prefix: /order/report
backend_orderout:
    resource: '@OrderBundle/Resources/config/routing/backend_out.yml'
    prefix: /order/out
backend_report:
    resource: '@ReportBundle/Resources/config/routing/backend.yml'
    prefix: /report
backend_google_drive:
    resource: '@GoogleBundle/Resources/config/routing/google_drive_file.yml'
    prefix: /google-drive
backend_google_drive_grid:
    resource: '@GoogleBundle/Resources/config/routing/google_drive_file_grid.yml'
    prefix: /google-drive-grid
backend_google_drive_vote:
    resource: '@GoogleBundle/Resources/config/routing/google_drive_file_vote.yml'
    prefix: /google-drive-vote
