backend_default:
    resource: '@BackendBundle/Resources/config/routing/default.yml'
    prefix: /

backend_product:
    resource: '@ProductBundle/Resources/config/routing/backend.yml'
    prefix: /product

#backend_user:
#    resource: '@UserBundle/Resources/config/routing/backend.yml'
#    prefix: /user
