backend_super_default:
    resource: '@BackendBundle/Resources/config/routing/default_super.yml'
    prefix: /
backend_super_role:
    resource: '@RoleBundle/Resources/config/routing/backend.yml'
    prefix: /role
backend_super_profile:
    resource: '@ProfileBundle/Resources/config/routing/backend.yml'
    prefix: /profile
backend_security_super:
    resource: '@UserBundle/Resources/config/routing/security_super.yml'
    prefix: /security
backend_super_session:
    resource: '@SessionBundle/Resources/config/routing/backend.yml'
    prefix: /session
backend_super_report:
    resource: '@ReportBundle/Resources/config/routing/backend.yml'
    prefix: /report
backend_super_pointofsale:
    resource: '@PointofsaleBundle/Resources/config/routing/backend.yml'
    prefix: /point-of-sale
backend_super_pointofsale_pdv_child:
    resource: '@PointofsaleBundle/Resources/config/routing/backend_pdv_child.yml'
    prefix: /point-of-sale-child
backend_super_module:
    resource: '@ModuleBundle/Resources/config/routing/backend.yml'
    prefix: /module
backend_super_user:
    resource: '@UserBundle/Resources/config/routing/backend.yml'
    prefix: /user


#backend_super_pointofsale_per_user:
#    resource: '@PointofsaleBundle/Resources/config/routing/backend_per_user.yml'
#    prefix: /point-of-sale-per-user
#backend_super_core:
#    resource: '@CoreBundle/Resources/config/routing/backend.yml'
#    prefix: /core
#backend_super_visit:
#    resource: '@VisitBundle/Resources/config/routing/backend.yml'
#    prefix: /visit
#backend_super_google_drive:
#    resource: '@GoogleBundle/Resources/config/routing/google_drive_file.yml'
#    prefix: /google-drive
#backend_super_google_drive_grid:
#    resource: '@GoogleBundle/Resources/config/routing/google_drive_file_grid.yml'
#    prefix: /google-drive-grid
#backend_super_google_drive_vote:
#    resource: '@GoogleBundle/Resources/config/routing/google_drive_file_vote.yml'
#    prefix: /google-drive-vote
#backend_super_user_client:
#    resource: '@UserBundle/Resources/config/routing/backend_client.yml'
#    prefix: /user-client
#backend_super_user_employee:
#    resource: '@UserBundle/Resources/config/routing/backend_employee.yml'
#    prefix: /user-employee
#backend_super_friends_user:
#    resource: '@UserBundle/Resources/config/routing/backend_friends.yml'
#    prefix: /user-friends
#backend_super_setting_user:
#    resource: '@UserBundle/Resources/config/routing/backend_setting.yml'
#    prefix: /user-setting
#backend_super_calendar:
#    resource: '@CalendarBundle/Resources/config/routing/backend.yml'
#    prefix: /calendar
#backend_super_product:
#    resource: '@ProductBundle/Resources/config/routing/backend.yml'
#    prefix: /product
#backend_super_category:
#    resource: '@CategoryBundle/Resources/config/routing/tree.yml'
#    prefix: /category
#backend_super_associative:
#    resource: '@AssociativeBundle/Resources/config/routing.yml'
#    prefix: /associative
#backend_super_groupofusers:
#    resource: '@GroupofusersBundle/Resources/config/routing/backend.yml'
#    prefix: /group-of-users
