backend_default:
    resource: '@BackendBundle/Resources/config/routing/default.yml'
    prefix: /

backend_product:
    resource: '@BackendBundle/Resources/config/routing/product.yml'
    prefix: /product

#backend_user:
#    resource: '@BackendBundle/Resources/config/routing/user.yml'
#    prefix: /user
#
#backend_session:
#    resource: '@BackendBundle/Resources/config/routing/session.yml'
#    prefix: /session