services:

    tianos.backend.controller.default:
        class: Bundle\BackendBundle\Controller\DefaultController
        arguments: [ Bundle\GridBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.backend.controller.default, alias: tianos.backend.controller.default }