services:

    tianos.backend.controller.default.super:
        class: Bundle\BackendBundle\Controller\DefaultSuperController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.backend.controller.default.super, alias: tianos.backend.controller.default.super }

    tianos.backend.controller.default.pdv:
        class: Bundle\BackendBundle\Controller\DefaultPdvController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.backend.controller.default.pdv, alias: tianos.backend.controller.default.pdv }