# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

#    always_authenticate_before_granting: true

    encoders:
        Bundle\UserBundle\Entity\User: bcrypt
#        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
#            id: fos_user.user_provider.username
            id: fos_user.user_provider.username_email
#    providers:
#        in_memory:
#            memory: ~

#/var/www/html/Tianos/vendor/friendsofsymfony/user-bundle/Resources/config/routing/security.xml


    firewalls:
#        main:
#            pattern: ^/
#            form_login:
#                provider: fos_userbundle
#                csrf_token_generator: security.csrf.token_manager
#                login_path: backend_security_login
#                check_path: fos_user_security_check
#                default_target_path: frontend_default_index
#                success_handler: tianos.authentication_success_handler
#                # if you are using Symfony < 2.8, use the following config instead:
#                # csrf_provider: form.csrf_provider
#            logout:
#                path: fos_user_security_logout
#                target: backend_security_login
#            remember_me:
##                token_provider: name
#                secret: "%secret%"
##                name: NameOfTheCookie
#                lifetime: 3600 # in seconds
#                secure: false
#                httponly: true
#                always_remember_me: false
#                remember_me_parameter: _remember_me
#            anonymous:    true
        main_super:
            pattern: ^/backend-super
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: backend_security_super_login
                check_path: backend_security_super_login_check
                default_target_path: backend_default_super_index
                success_handler: tianos.authentication_success_handler
                failure_handler: tianos.authentication_failure_handler
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            logout:
                path: backend_security_super_logout
                target: backend_security_super_login
            remember_me:
#                token_provider: name
                secret: "%secret%"
#                name: NameOfTheCookie
                lifetime: 3600 # in seconds
                secure: false
                httponly: true
                always_remember_me: false
                remember_me_parameter: _remember_me
            anonymous:    true
        main_pdv:
            pattern: ^/backend
            form_login:
                provider: fos_userbundle
#                csrf_token_generator: security.csrf.token_manager
                login_path: backend_security_pdv_login
                check_path: backend_security_pdv_login_check
                default_target_path: backend_default_pdv_index
                success_handler: tianos.authentication_success_handler
                failure_handler: tianos.authentication_failure_handler
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            logout:
                path: backend_security_pdv_logout
                target: backend_security_pdv_login
            remember_me:
#                token_provider: name
                secret: "%secret%"
#                name: NameOfTheCookie
                lifetime: 3600 # in seconds
                secure: false
                httponly: true
                always_remember_me: false
                remember_me_parameter: _remember_me
            anonymous:    true
#        main_pdv_login:
#            pattern: ^/login
#            form_login:
#                provider: fos_userbundle
##                csrf_token_generator: security.csrf.token_manager
#                login_path: backend_security_pdv_login
#                check_path: backend_security_pdv_login_check
#                default_target_path: backend_default_pdv_index
#                success_handler: tianos.authentication_success_handler
#                # if you are using Symfony < 2.8, use the following config instead:
#                # csrf_provider: form.csrf_provider
#            logout:
#                path: backend_security_pdv_logout
#                target: backend_security_pdv_login
#            remember_me:
##                token_provider: name
#                secret: "%secret%"
##                name: NameOfTheCookie
#                lifetime: 3600 # in seconds
#                secure: false
#                httponly: true
#                always_remember_me: false
#                remember_me_parameter: _remember_me
#            anonymous:    true
    access_control:
#        - { path: ^/login/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/login/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/backend/security/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/backend/security/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend-super/security/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/backend/security/login-facebook-callback$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/backend/security/reset-password-step-one$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/backend/security/reset-password-step-two$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/backend/security/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/user/, role: ROLE_USER }
        - { path: ^/backend/, role: [ROLE_PDV_ADMIN, ROLE_EMPLOYEE] }
        - { path: ^/backend-super/, role: ROLE_SUPER_ADMIN }


#    firewalls:
#        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            anonymous: ~
#            # activate different ways to authenticate
#
#            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#            #http_basic: ~
#
#            # https://symfony.com/doc/current/security/form_login_setup.html
#            #form_login: ~
