#http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/yaml-mapping.html

Bundle\OrderBundle\Entity\Order:
    type: entity
    table: order_
    repositoryClass: Bundle\OrderBundle\Doctrine\ORM\OrderRepository
    indexes:
        fk_order_in_point_of_sale1_idx:
            columns:
                - point_of_sale_id
        fk_order_in_product1_idx:
            columns:
                - product_id
        fk_order_in_user1_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        quantity:
            type: integer
            nullable: true
            options:
                unsigned: false
        type:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        orderDate:
            type: datetime
            nullable: false
            column: order_date
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        isActive:
            type: boolean
            nullable: true
            column: is_active
    manyToOne:
        pointOfSale:
            targetEntity: Bundle\PointofsaleBundle\Entity\Pointofsale
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                point_of_sale_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Bundle\UserBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        product:
            targetEntity: Bundle\ProductBundle\Entity\Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }