#http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/yaml-mapping.html

Bundle\FilesBundle\Entity\Files:
    type: entity
    table: files
    repositoryClass: Bundle\FilesBundle\Doctrine\ORM\FilesRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        pkFileItem:
            type: integer
            nullable: false
            length: 150
            options:
                fixed: false
            column: pk_file_item
        mimeContentType:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: mime_content_type
        fileType:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: file_type
        filter:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: filter
        uniqid:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
#            gedmo:
#                timestampable:
#                    on: create
        userCreate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        userUpdate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_update
        isActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: is_active
    lifecycleCallbacks: {  }
#    lifecycleCallbacks:
#        prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]
#        postPersist: [ doStuffOnPostPersist ]
