#http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/yaml-mapping.html

Bundle\ServicesBundle\Entity\Services:
    type: entity
#    type: mappedSuperclass
#    mappedSuperclass: Component\CRUDDUMMY\Model\CRUDDUMMY
    table: services
    repositoryClass: Bundle\ServicesBundle\Doctrine\ORM\ServicesRepository
    indexes:
        fk_product_category1_idx:
            columns:
                - category_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        price:
            type: float
            nullable: true
            precision: 8
            scale: 2
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        slug:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
#        image:
#            type: string
#            nullable: true
#            length: 45
#            options:
#                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
#            gedmo:
#                timestampable:
#                    on: create
        userCreate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        userUpdate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_update
        isActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: is_active
    manyToOne:
        category:
            targetEntity: Bundle\CategoryBundle\Entity\Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
#    lifecycleCallbacks:
#        prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]
#        postPersist: [ doStuffOnPostPersist ]
