backend_route_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.route:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            vars:
                subheader: sylius.ui.manage_your_route_catalog
                icon: cube
                body_css: grid-body-css
            grid:
                icon: road
                box_class: primary
                title: Gestionar ruta
                data_table:
                    route:
                        info: backend_route_info
                        view: backend_route_view
                        edit: backend_route_edit
                        create: backend_route_create
                        delete: backend_route_delete
                    table_button:
                        - edit
                        - delete
                    table_button_header:
                        - create
                        - info
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
                    columns:
                        - name: '#'
                          obj: " '<span class=\"badge bg-blue\">' + obj.id + '</span>' "
                        - name: Name
                          obj: obj.name
                        - name: Creado
                          obj: obj.created_at
                          options:
                              icon: calendar
            form:
                type: Bundle\RouteBundle\Form\Type\RouteType
            repository:
                service: tianos.repository.route
                method: findAll
                arguments: [$routeId]
                vars:
                    serialize_group_name: crud

backend_route_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.route:createAction
        _tianos:
            action: create
            template: RouteBundle:RouteBackend/Form:form.html.twig
            entity: Bundle\RouteBundle\Entity\Route
            form:
                type: Bundle\RouteBundle\Form\Type\RouteType
            repository:
                vars:
                    serialize_group_name: crud

backend_route_edit:
    path: /edit
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.route:editAction
        _tianos:
            action: edit
            template: RouteBundle:RouteBackend/Form:form.html.twig
            form:
                type: Bundle\RouteBundle\Form\Type\RouteType
            repository:
                service: tianos.repository.route
                method: find
                arguments: [$routeId]
                vars:
                    serialize_group_name: crud

backend_route_delete:
    path: /delete
    methods: [POST, DELETE]
    defaults:
        _controller: tianos.backend.controller.route:deleteAction
        _tianos:
            action: delete
            template: GridBundle:Template:delete.html.twig
            repository:
                service: tianos.repository.route
                method: find
                arguments: [$routeId]
            vars:
#                body_css: grid-body-css

backend_route_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.route:viewAction
        _tianos:
            action: view
            template: RouteBundle:RouteBackend/Informative:view.html.twig
            repository:
                service: tianos.repository.route
                method: find
                arguments: [$routeId]
                vars:
                    serialize_group_name: crud

backend_route_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.route:infoAction
        _tianos:
            action: info
            template: RouteBundle:RouteBackend/Informative:info.html.twig