backend_category_tree_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.tree.controller.category:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: TreeBundle::index.html.twig
            vars:
                subheader: sylius.ui.manage_your_category_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
#            grid: sylius_admin_product
            tree:
                icon: cube
                box_class: primary
                title: Gestionar category
                data_table:
                    route:
                        info: backend_category_tree_info
                        view: backend_category_tree_view
                        edit: backend_category_tree_edit
                        create: backend_category_tree_create
                        delete: backend_category_tree_delete
                    table_button:
                        - edit
                        - delete
                    table_button_header:
                        - create
                        - info
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
#                    columns:
#                        - name: '#'
#                          obj: " '<span class=\"badge bg-blue\">' + obj.id + '</span>' "
##                        - name: code
##                          obj: obj.code
##                          options:
##                              icon: map-marker
#                        - name: Name
#                          obj: obj.name
##                        - name: slug
##                          obj: obj.slug
#                        - name: Creado
#                          obj: obj.createdAt
#                          options:
#                              icon: calendar
            form:
                type: Bundle\CategoryBundle\Form\Type\CategoryType
            repository:
                service: tianos.repository.category
                method: findAll
                arguments: [$categoryId]

backend_category_tree_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: tianos.tree.controller.category:createAction
        _tianos:
            action: create
            template: CategoryBundle:CategoryBackend/Form:form.html.twig
            entity: Bundle\CategoryBundle\Entity\Category
            form:
                type: Bundle\CategoryBundle\Form\Type\CategoryType
            vars:
                serialize_group_name: crud

backend_category_tree_edit:
    path: /edit
    methods: [PUT, POST]
    defaults:
        _controller: tianos.tree.controller.category:editAction
        _tianos:
            action: edit
            template: CategoryBundle:CategoryBackend/Form:form.html.twig
            repository:
                service: tianos.repository.category
                method: find
                arguments: [$categoryId]
            form:
                type: Bundle\CategoryBundle\Form\Type\CategoryType
            vars:
                serialize_group_name: crud

backend_category_tree_delete:
    path: /delete
    methods: [POST, DELETE]
    defaults:
        _controller: tianos.tree.controller.category:deleteAction
        _tianos:
            action: delete
            template: GridBundle:Template:delete.html.twig
            repository:
                service: tianos.repository.category
                method: find
                arguments: [$categoryId]
            vars:
#                body_css: grid-body-css

backend_category_tree_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.tree.controller.category:viewAction
        _tianos:
            action: view
            template: CategoryBundle:CategoryBackend/Informative:view.html.twig
            repository:
                service: tianos.repository.category
                method: find
                arguments: [$categoryId]

backend_category_tree_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.tree.controller.category:infoAction
        _tianos:
            action: info
            template: CategoryBundle:CategoryBackend/Informative:info.html.twig