backend_pointofsale_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.pointofsale:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            vars:
                subheader: sylius.ui.manage_your_pointofsale_catalog
                icon: cube
                body_css: grid-body-css
                google_maps: true
                copy_clipboard: true
            grid:
                icon: map-marker
                box_class: primary
                title: Gestionar puntos de ventas
                modal:
                    create:
                        title: Crear punto de venta
                        size: modal-lg
                    edit:
                        title: Editar punto de venta
                        size: modal-lg
                data_table:
                    route:
                        info: backend_pointofsale_info
                        view: backend_pointofsale_view
                        edit: backend_pointofsale_edit
                        create: backend_pointofsale_create
                        delete: backend_pointofsale_delete
                        cog: backend_super_pointofsale_add_user_index
                    table_button:
                        - edit
                        - delete
                        - cog
                    table_button_header:
                        - create
                        - info
                    table_option:
                        pageLength: 50
                        dom: "'<\"top\"iflp><\"clear\">rt<\"bottom\"iflp>'"
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
                    columns:
                        - name: '#'
                          obj: " '<span class=\"badge bg-blue\">' + obj.id + '</span>' "
                        - name: Nombre
                          obj: obj.name
                        - name: Coordenadas
                          obj: " '<span class=\"badge bg-green\">' + obj.latitude + ' :: ' + obj.longitude + '</span>' "
                          options:
                              icon: map-marker
                        - name: Dias creado
                          obj: " '<span class=\"badge bg-blue\">' + obj.created_at_diff + '</span>' "
                          options:
                              icon: clock-o
                        - name: Creado
                          obj: obj.created_at
                          options:
                              icon: calendar
            form:
                type: Bundle\PointofsaleBundle\Form\Type\PointofsaleType
            repository:
                service: tianos.repository.pointofsale
                method: findAllParents
                arguments: [$pointofsaleId]
                vars:
                    serialize_group_name: crud

backend_pointofsale_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.pointofsale:createAction
        _tianos:
            action: create
            template: PointofsaleBundle:BackendPointofsale/Form:form_create.html.twig
            entity: Bundle\PointofsaleBundle\Entity\Pointofsale
            form:
                type: Bundle\PointofsaleBundle\Form\Type\PointofsaleType
            repository:
                vars:
                    serialize_group_name: crud

backend_pointofsale_edit:
    path: /edit
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.pointofsale:editAction
        _tianos:
            action: edit
            template: PointofsaleBundle:BackendPointofsale/Form:form_edit.html.twig
            entity: Bundle\PointofsaleBundle\Entity\Pointofsale
            form:
                type: Bundle\PointofsaleBundle\Form\Type\PointofsaleType
            repository:
                service: tianos.repository.pointofsale
                method: find
                arguments: [$pointofsaleId]
                vars:
                    serialize_group_name: crud

backend_pointofsale_delete:
    path: /delete
    methods: [POST, DELETE]
    defaults:
        _controller: tianos.backend.controller.pointofsale:deleteAction
        _tianos:
            action: delete
            template: GridBundle:Template:delete.html.twig
            repository:
                service: tianos.repository.pointofsale
                method: find
                arguments: [$pointofsaleId]
            vars:
#                body_css: grid-body-css

backend_pointofsale_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.pointofsale:viewAction
        _tianos:
            action: view
            template: PointofsaleBundle:BackendPointofsale/Informative:view.html.twig
            repository:
                service: tianos.repository.pointofsale
                method: findParentAndChildren
                arguments: [$pointofsaleId]
                vars:
                    serialize_group_name: crud

backend_pointofsale_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.pointofsale:infoAction
        _tianos:
            action: info
            template: PointofsaleBundle:BackendPointofsale/Informative:info.html.twig

backend_pointofsale_module:
    path: /module/{id}
    methods: [GET, POST]
    defaults:
        _controller: tianos.backend.controller.pointofsale:moduleAction
        _tianos:
            action: edit
            template: PointofsaleBundle:BackendPointofsale:module.html.twig
            entity: Bundle\PointofsaleBundle\Entity\PointofsaleModule
            vars:
                icon: map-marker
                box_class: primary
                title: 'Punto de venta: agregar modulos'
                body_css: grid-body-css
                copy_clipboard: true
            form:
                type: Bundle\PointofsaleBundle\Form\Type\PointofsaleModuleType
            repository:
                service: tianos.repository.pointofsale
                method: find
                arguments: [$pointofsaleId]
                vars:
                    serialize_group_name: crud
