backend_associativeacademic_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.associativeacademic:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: AssociativeacademicBundle:BackendAssociativeacademic:index.html.twig
            vars:
                subheader: sylius.ui.manage_your_associativeacademic_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
                box:
                    icon: book
                    class: primary
                    box_class: primary
                    form_name: main-form
                    title: Asociación del bloque académico <i class="fa fa-angle-double-right"></i>
                    route_submit: backend_orderin_upsert
                    route_info: backend_associativeacademic_info
                    table_button_header:
                        - info
                box_one:
                    icon: building
                    class: primary
                    id: box-one-id
                    title: Universidades
                    li_class: box-one-li
                    li_badge_class: bg-green
                    li_input_radio_name: box-one-selected-value
                    search_input_name: search-input-name-one
                    route_search: backend_associativeacademic_one_search
                    route_select_item: backend_associativeacademic_one_select_item
                box_two:
                    icon: bookmark
                    class: primary
                    id: box-two-id
                    title: Áreas académicas
                    li_class: box-two-li
                    li_badge_class: bg-orange-active
                    li_input_radio_name: box-two-selected-radio
                    li_input_checkbox_name: box-two-selected-checkbox
                    search_input_name: search-input-name-two
                    route_search: backend_associativeacademic_two_search
                    route_select_item: backend_associativeacademic_two_select_item
                    route_up_serting: backend_associativeacademic_two_up_serting
                box_three:
                    icon: building-o
                    class: primary
                    id: box-three-id
                    title: Facultades
                    li_class: box-three-li
                    li_badge_class: bg-orange-active
                    li_input_radio_name: box-three-selected-radio
                    li_input_checkbox_name: box-three-selected-checkbox
                    search_input_name: search-input-name-three
                    route_search: backend_associativeacademic_three_search
                    route_select_item: backend_associativeacademic_three_select_item
                    route_up_serting: backend_associativeacademic_three_up_serting
                box_four:
                    icon: bell-o
                    class: primary
                    id: box-four-id
                    title: Escuelas
                    li_class: box-four-li
                    li_badge_class: bg-orange-active
                    li_input_name: box-four-selected-value
                    search_input_name: search-input-name-four
                    route_search: backend_associativeacademic_four_search
                    route_select_item: backend_associativeacademic_four_select_item
            form:
                type: Bundle\AssociativeacademicBundle\Form\Type\AssociativeacademicType
            repository:
                service: tianos.repository.university
                method: findAll
                arguments:
                    limit: 20
                vars:
                    serialize_group_name: associative-academic

backend_associativeacademic_one_search:
    path: /one-search
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.associativeacademic:boxOneSearchAction
        _tianos:
            action: one_search
            template: AssociativeacademicBundle:BackendAssociativeacademic/Li:1_box_one.html.twig
            vars:
                box_one:
                    li_class: box-one-li
                    li_badge_class: bg-green
                    li_input_name: box-one-selected-value
                    search_input_name: search-input-name-one
            repository:
                service: tianos.repository.university
                method: searchBox
                arguments:
                    limit: 20
                vars:
                    serialize_group_name: associative-academic

backend_associativeacademic_two_search:
    path: /two-search
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.associativeacademic:boxTwoSearchAction
        _tianos:
            action: two_search
            template: AssociativeacademicBundle:BackendAssociativeacademic/Li:2_box_two_search.html.twig
            vars:
                box_two:
                    li_class: box-two-li
                    li_badge_class: bg-blue
                    li_input_radio_name: box-two-selected-radio
                    li_input_checkbox_name: box-two-selected-checkbox
                    search_input_name: search-input-name-two
            repository:
                service: tianos.repository.areaacademica
                method: searchBox
                arguments:
                    limit: 20
                vars:
                    serialize_group_name: associative-academic

backend_associativeacademic_three_search:
    path: /three-search
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.associativeacademic:boxThreeSearchAction
        _tianos:
            action: three_search
            template: AssociativeacademicBundle:BackendAssociativeacademic/Li:3_box_three_search.html.twig
            vars:
                box_three:
                    li_class: box-three-li
                    li_badge_class: bg-orange-active
                    li_input_radio_name: box-three-selected-radio
                    li_input_checkbox_name: box-three-selected-checkbox
                    search_input_name: search-input-name-three
            repository:
                service: tianos.repository.facultad
                method: searchBox
                arguments:
                    limit: 20
                vars:
                    serialize_group_name: associative-academic

backend_associativeacademic_four_search:
    path: /four-search
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.associativeacademic:boxFourSearchAction
        _tianos:
            action: four_search
            template: AssociativeacademicBundle:BackendAssociativeacademic/Li:4_box_four_search.html.twig
            vars:
                box_four:
                    li_class: box-four-li
                    li_badge_class: bg-green
                    li_input_name: box-four-selected-value
                    search_input_name: search-input-name-four
            repository:
                service: tianos.repository.escuela
                method: searchBox
                arguments:
                    limit: 20
                vars:
                    serialize_group_name: associative-academic

backend_associativeacademic_one_select_item:
    path: /one-select-item
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.associativeacademic:boxOneSelectItemAction
        _tianos:
            template: AssociativeacademicBundle:BackendAssociativeacademic/Li:2_box_two_select_item.html.twig
            vars:
                box_one:
                    li_class: box-one-li
                    li_badge_class: bg-green
                    search_input_name: search-input-name-one
                box_two:
                    entity: areaacademica
                    li_class: box-two-li
                    li_badge_class: bg-blue
                    li_input_radio_name: box-two-selected-radio
                    li_input_checkbox_name: box-two-selected-checkbox
            repository:
                service: tianos.repository.university
                method: find
                arguments:
                    limit: 20
                vars:
                    serialize_group_name: associative-academic

backend_associativeacademic_two_select_item:
    path: /two-select-item
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.associativeacademic:boxTwoSelectItemAction
        _tianos:
            template: AssociativeacademicBundle:BackendAssociativeacademic/Li:3_box_three_select_item.html.twig
            vars:
                box_two:
                    li_class: box-two-li
                    li_badge_class: bg-blue
                    li_input_radio_name: box-two-selected-radio
                    li_input_checkbox_name: box-two-selected-checkbox
                box_three:
                    entity: facultad
                    li_class: box-three-li
                    li_badge_class: bg-orange-active
                    li_input_radio_name: box-three-selected-radio
                    li_input_checkbox_name: box-three-selected-checkbox
            repository:
                service: tianos.repository.areaacademica
                method: find
                arguments:
                    limit: 20
                vars:
                    serialize_group_name: associative-academic

backend_associativeacademic_two_up_serting:
    path: /two-up-serting
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.associativeacademic:boxTwoUpSertingAction
        _tianos:
            vars:
#                box_two:
#                    li_class: box-two-li
#                    li_badge_class: bg-blue
#                    li_input_name: box-two-selected-value
#                box_three:
#                    entity: facultad
#                    li_class: box-three-li
#                    li_badge_class: bg-orange-active
#                    li_input_name: box-three-selected-value
            repository:
                box_one:
                    service: tianos.repository.university
                    method: associative
                    arguments:
                        limit: 20
                    vars:
                        serialize_group_name: associative-academic
                box_two:
                    service: tianos.repository.areaacademica
                    method: find
                    arguments:
                        limit: 20
                    vars:
                        serialize_group_name: associative-academic

backend_associativeacademic_three_select_item:
    path: /three-select-item
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.associativeacademic:boxThreeSelectItemAction
        _tianos:
            template: AssociativeacademicBundle:BackendAssociativeacademic/Li:4_box_four_select_item.html.twig
            vars:
                box_three:
                    li_class: box-three-li
                    li_badge_class: bg-orange-active
                    li_input_name: box-three-selected-value
                box_four:
                    entity: escuela
                    li_class: box-four-li
                    li_badge_class: bg-teal-active
                    li_input_name: box-four-selected-value
            repository:
                service: tianos.repository.facultad
                method: find
                arguments:
                    limit: 20
                vars:
                    serialize_group_name: associative-academic

backend_associativeacademic_three_up_serting:
    path: /three-up-serting
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.associativeacademic:boxThreeUpSertingAction
        _tianos:
            vars:
#                box_three:
#                    li_class: box-three-li
#                    li_badge_class: bg-orange-active
#                    li_input_name: box-three-selected-value
#                box_four:
#                    entity: escuela
#                    li_class: box-four-li
#                    li_badge_class: bg-teal-active
#                    li_input_name: box-four-selected-value
            repository:
                box_two:
                    service: tianos.repository.areaacademica
                    method: associative
                    arguments:
                        limit: 20
                    vars:
                        serialize_group_name: associative-academic
                box_three:
                    service: tianos.repository.facultad
                    method: find
                    arguments:
                        limit: 20
                    vars:
                        serialize_group_name: associative-academic

backend_associativeacademic_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.associativeacademic:infoAction
        _tianos:
            action: info
            template: AssociativeacademicBundle:BackendAssociativeacademic/Informative:info.html.twig
