backend_associativeacademic_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.associativeacademic:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: AssociativeacademicBundle:BackendAssociativeacademic:index.html.twig
            vars:
                subheader: sylius.ui.manage_your_associativeacademic_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
                box:
                    icon: book
                    class: primary
                    box_class: primary
                    form_name: main-form
                    title: Asociación del bloque académico <i class="fa fa-angle-double-right"></i>
                    route_submit: backend_orderin_upsert
                    route_info: backend_associativeacademic_info
                    table_button_header:
                        - info
                box_one:
                    icon: building
                    class: primary
                    id: box-one-id
                    title: Universidades
                    li_class: box-left-li
                    li_badge_class: bg-green
                    li_input_name: box_left_selected_value
                    search_input_name: search-input-name-one
                    route_search: backend_associativeacademic_one_search
                    route_select_item: backend_orderin_boxleft_select_item
                box_two:
                    icon: bookmark
                    class: primary
                    id: box-two-id
                    title: Áreas académicas
                    li_class: box-center-li
                    li_badge_class: bg-orange-active
                    li_input_name: box_center_selected_value
                    search_input_name: search-input-name-two
                    route_search: backend_orderin_search
                    route_select_item: backend_orderin_boxcenter_select_item
                box_three:
                    icon: building-o
                    class: primary
                    id: box-three-id
                    title: Facultades
                    li_class: box-right-li
                    li_badge_class: bg-orange-active
                    li_input_name: box-right-selected-value
                    search_input_name: search-input-name-three
                    route_search: backend_orderin_search
                    route_select_item: backend_orderin_boxcenter_select_item
                box_four:
                    icon: bell-o
                    class: primary
                    id: box-four-id
                    title: Escuelas
                    li_class: box-right-li
                    li_badge_class: bg-orange-active
                    li_input_name: box-right-selected-value
                    search_input_name: search-input-name-four
                    route_search: backend_orderin_search
                    route_select_item: backend_orderin_boxcenter_select_item
            form:
                type: Bundle\AssociativeacademicBundle\Form\Type\AssociativeacademicType
            repository:
                box_left:
                    service: tianos.repository.university
                    method: findAll
                    arguments:
                        limit: 20
                    vars:
                        serialize_group_name: associative-academic

backend_associativeacademic_one_search:
    path: /one-search
    methods: [POST]
    defaults:
        _controller: tianos.backend.in.controller.order:boxOneSearchAction
        _tianos:
            action: left_search
            template: OrderBundle:OrderInBackend/Li:box_left.html.twig
            template: AssociativeacademicBundle:BackendAssociativeacademic/Li:1_box_one.html.twig
            vars:
                box_left:
                    li_class: box-one-li
                    li_badge_class: bg-blue
                    li_input_name: box-one-selected-value
                    search_input_name: search-input-name-one
            repository:
                box_left:
                    service: tianos.repository.university
                    method: searchBox
                    arguments:
                        limit: 20
                    vars:
                        serialize_group_name: one-search

backend_associativeacademic_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.associativeacademic:infoAction
        _tianos:
            action: info
            template: AssociativeacademicBundle:BackendAssociativeacademic/Informative:info.html.twig









#
#backend_associativeacademic_create:
#    path: /create
#    methods: [POST]
#    defaults:
#        _controller: tianos.backend.controller.associativeacademic:createAction
#        _tianos:
#            action: create
#            template: AssociativeacademicBundle:BackendAssociativeacademic/Form:form.html.twig
#            entity: Bundle\AssociativeacademicBundle\Entity\Associativeacademic
#            form:
#                type: Bundle\AssociativeacademicBundle\Form\Type\AssociativeacademicType
#            repository:
#                vars:
#                    serialize_group_name: crud
#
#backend_associativeacademic_edit:
#    path: /edit
#    methods: [PUT, POST]
#    defaults:
#        _controller: tianos.backend.controller.associativeacademic:editAction
#        _tianos:
#            action: edit
#            template: AssociativeacademicBundle:BackendAssociativeacademic/Form:form.html.twig
#            form:
#                type: Bundle\AssociativeacademicBundle\Form\Type\AssociativeacademicType
#            repository:
#                service: tianos.repository.associativeacademic
#                method: find
#                arguments: [$associativeacademicId]
#                vars:
#                    serialize_group_name: crud
#
#backend_associativeacademic_delete:
#    path: /delete
#    methods: [POST, DELETE]
#    defaults:
#        _controller: tianos.backend.controller.associativeacademic:deleteAction
#        _tianos:
#            action: delete
#            template: GridBundle:Template:delete.html.twig
#            repository:
#                service: tianos.repository.associativeacademic
#                method: find
#                arguments: [$associativeacademicId]
#            vars:
##                body_css: grid-body-css
#
#backend_associativeacademic_view:
#    path: /view
#    methods: [POST]
#    defaults:
#        _controller: tianos.backend.controller.associativeacademic:viewAction
#        _tianos:
#            action: view
#            template: AssociativeacademicBundle:BackendAssociativeacademic/Informative:view.html.twig
#            repository:
#                service: tianos.repository.associativeacademic
#                method: find
#                arguments: [$associativeacademicId]
#                vars:
#                    serialize_group_name: crud



