backend_associativeacademic_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.associativeacademic:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            vars:
                subheader: sylius.ui.manage_your_associativeacademic_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
#            grid: sylius_admin_product
            grid:
                icon: cube
                box_class: primary
                title: Gestionar associativeacademic
                data_table:
                    route:
                        info: backend_associativeacademic_info
                        view: backend_associativeacademic_view
                        edit: backend_associativeacademic_edit
                        create: backend_associativeacademic_create
                        delete: backend_associativeacademic_delete
                    table_button:
                        - edit
                        - delete
                    table_button_header:
                        - create
                        - info
                    table_option:
                        pageLength: 10
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
                    columns:
                        - name: '#'
                          obj: " '<span class=\"badge bg-blue\">' + obj.id + '</span>' "
                        - name: Name
                          obj: obj.name
                        - name: Creado
                          obj: obj.created_at
                          options:
                              icon: calendar
            form:
                type: Bundle\AssociativeacademicBundle\Form\Type\AssociativeacademicType
            repository:
                service: tianos.repository.associativeacademic
                method: findAll
                arguments: [$associativeacademicId]
                vars:
                    serialize_group_name: crud





backend_orderin_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.in.controller.order:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: OrderBundle:OrderInBackend:index.html.twig
            vars:
                subheader: sylius.ui.manage_your_orderin_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
                box:
                    icon: newspaper-o
                    class: primary
                    box_class: primary
                    form_name: main-form
                    title: Devoluci贸n de peri贸dicos por los Canillitas <i class="fa fa-sign-in"></i>
                    route_submit: backend_orderin_upsert
                    route_info: backend_orderin_info
                    table_button_header:
                        - create
                        - info
                box_one:
                    icon: map-marker
                    class: primary
                    id: box-left-id
                    title: Puntos de venta
                    li_class: box-left-li
                    li_badge_class: bg-green
                    li_input_name: box_left_selected_value
                    search_input_name: search-input-name-left
                    route_search: backend_orderin_search
                    route_select_item: backend_orderin_boxleft_select_item
                box_two:
                    icon: user
                    class: primary
                    id: box-center-id
                    title: Canillitas
                    li_class: box-center-li
                    li_badge_class: bg-orange-active
                    li_input_name: box_center_selected_value
                    route_select_item: backend_orderin_boxcenter_select_item
                box_three:
                    icon: newspaper-o
                    class: primary
                    id: box-right-id
                    title: Peri贸dicos
                    li_class: box-right-li
                    li_badge_class: bg-orange-active
                    li_input_name: box-right-selected-value
                box_four:
                    icon: newspaper-o
                    class: primary
                    id: box-right-id
                    title: Peri贸dicos
                    li_class: box-right-li
                    li_badge_class: bg-orange-active
                    li_input_name: box-right-selected-value
            grid:
#                icon: cube
#                box_class: primary
#                title: Gestionar productos
#                modal:
#                    title: Crear producto
                data_table:
                    route:
                    table_button:
                    table_button_header:
                        - info
                    row_call_back:
                    columns:
            form:
                type: Bundle\OrderBundle\Form\Type\OrderinType
            repository:
                box_left:
                    service: tianos.repository.pointofsale
                    method: findAllOffsetLimit
                    arguments:
                        limit: 20
                    vars:
                        serialize_group_name: order-in-left














#
#backend_associativeacademic_create:
#    path: /create
#    methods: [POST]
#    defaults:
#        _controller: tianos.backend.controller.associativeacademic:createAction
#        _tianos:
#            action: create
#            template: AssociativeacademicBundle:BackendAssociativeacademic/Form:form.html.twig
#            entity: Bundle\AssociativeacademicBundle\Entity\Associativeacademic
#            form:
#                type: Bundle\AssociativeacademicBundle\Form\Type\AssociativeacademicType
#            repository:
#                vars:
#                    serialize_group_name: crud
#
#backend_associativeacademic_edit:
#    path: /edit
#    methods: [PUT, POST]
#    defaults:
#        _controller: tianos.backend.controller.associativeacademic:editAction
#        _tianos:
#            action: edit
#            template: AssociativeacademicBundle:BackendAssociativeacademic/Form:form.html.twig
#            form:
#                type: Bundle\AssociativeacademicBundle\Form\Type\AssociativeacademicType
#            repository:
#                service: tianos.repository.associativeacademic
#                method: find
#                arguments: [$associativeacademicId]
#                vars:
#                    serialize_group_name: crud
#
#backend_associativeacademic_delete:
#    path: /delete
#    methods: [POST, DELETE]
#    defaults:
#        _controller: tianos.backend.controller.associativeacademic:deleteAction
#        _tianos:
#            action: delete
#            template: GridBundle:Template:delete.html.twig
#            repository:
#                service: tianos.repository.associativeacademic
#                method: find
#                arguments: [$associativeacademicId]
#            vars:
##                body_css: grid-body-css
#
#backend_associativeacademic_view:
#    path: /view
#    methods: [POST]
#    defaults:
#        _controller: tianos.backend.controller.associativeacademic:viewAction
#        _tianos:
#            action: view
#            template: AssociativeacademicBundle:BackendAssociativeacademic/Informative:view.html.twig
#            repository:
#                service: tianos.repository.associativeacademic
#                method: find
#                arguments: [$associativeacademicId]
#                vars:
#                    serialize_group_name: crud

backend_associativeacademic_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.associativeacademic:infoAction
        _tianos:
            action: info
            template: AssociativeacademicBundle:BackendAssociativeacademic/Informative:info.html.twig





#/var/www/html/Sylius/sylius/vendor/sylius/sylius/docs/customization/factory.rst
#
#    sylius_admin_product_create_simple:
#        path: /products/new/simple
#        methods: [GET, POST]
#        defaults:
#            _controller: sylius.controller.product:createAction
#            _sylius:
#                section: admin
#                factory:
#                    method: createDisabled # like here for example
#                template: SyliusAdminBundle:Crud:create.html.twig
#                redirect: sylius_admin_product_update
#                vars:
#                    subheader: sylius.ui.manage_your_product_catalog
#                    templates:
#                        form: SyliusAdminBundle:CRUDDUMMY:_form.html.twig
#                    route:
#                        name: sylius_admin_product_create_simple



#            template: "@SyliusAdmin/ProductVariant/generate.html.twig"
#            section: admin
#            permission: true
#            redirect:
#                route: sylius_admin_product_variant_index
#                parameters: { productId: $productId }
#            form:
#                type: Sylius\Bundle\ProductBundle\Form\Type\ProductGenerateVariantsType
#            repository:
#                method: find
#                arguments: [$productId]
#            flash: sylius.product_variant.generate

#sylius_admin_product_index:
#    path: /products/
#    methods: [GET]
#    defaults:
#        _controller: sylius.controller.product:indexAction
#        _sylius:
#            section: admin
#            permission: true
#            grid: sylius_admin_product
#            template: SyliusAdminBundle:CRUDDUMMY:index.html.twig
#            vars:
#                subheader: sylius.ui.manage_your_product_catalog
#                icon: cube
