frontend_associativeacademic_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.frontend.controller.associativeacademic:indexAction
        _tianos:
            section: admin
            permission: true
            grid: sylius_admin_associativeacademic
            template: AssociativeacademicBundle:Associativeacademic:index.html.twig
            vars:
                subheader: sylius.ui.manage_your_associativeacademic_catalog
                icon: cube
            form:
                type: Bundle\AssociativeacademicBundle\Form\Type\AssociativeacademicType
            repository:
                service: tianos.repository.associativeacademic
                method: findAll
                arguments: [$associativeacademicId]
