Bundle\RoleBundle\Entity\Role:
    type: entity
    table: role
    repositoryClass: Bundle\RoleBundle\Doctrine\ORM\RoleRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        groupRol:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: group_rol
        groupRolTag:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: group_rol_tag
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        userCreate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        userUpdate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_update
        isActive:
            type: boolean
            nullable: false
            column: is_active
    manyToMany:
        profile:
            targetEntity: Bundle\ProfileBundle\Entity\Profile
            cascade: {  }
            fetch: LAZY
            mappedBy: role
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
