services:

    tianos.listener.doctrine.pdvhasproduct:
        class: Bundle\PdvhasproductBundle\EventListener\DoctrineListenerService
        arguments: ["@security.token_storage"]
        tags:
          - { name: doctrine.event_listener, event: postUpdate }
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: postLoad }
          - { name: doctrine.event_listener, event: postRemove }

    tianos.api.controller.pdvhasproduct:
        class: Bundle\PdvhasproductBundle\Controller\ApiController
        arguments: [ Bundle\GridBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.api.controller.pdvhasproduct, alias: tianos.api.controller.pdvhasproduct }

    tianos.backend.controller.pdvhasproduct:
        class: Bundle\PdvhasproductBundle\Controller\BackendController
        arguments: [ Bundle\GridBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.backend.controller.pdvhasproduct, alias: tianos.backend.controller.pdvhasproduct }

    tianos.frontend.controller.pdvhasproduct:
        class: Bundle\PdvhasproductBundle\Controller\FrontendController
        arguments: [ Bundle\GridBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.frontend.controller.pdvhasproduct, alias: tianos.frontend.controller.pdvhasproduct }

    tianos.repository.pdvhasproduct:
        class: Dummy
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Bundle\PdvhasproductBundle\Entity\Pdvhasproduct ]



#    tianos.controller.grid:
#        class: Bundle\GridBundle\Controller\GridController
#        arguments: [ Bundle\GridBundle\Controller\RequestConfigurationFactoryInterface ]
#        tags:
#            - { name: tianos.controller.grid, alias: tianos.controller.grid }