backend_orderin_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.orderin:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: OrderinBundle:OrderinBackend:index.html.twig
            vars:
                subheader: sylius.ui.manage_your_orderin_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
                box:
                    icon: newspaper-o
                    class: primary
                    box_class: primary
                    form_name: main-form
                    title: Devolución de periódicos por los Canillitas
                    route_info: backend_associative_profile_has_role_info
                    table_button_header:
                        - create
                        - info
                box_left:
                    icon: map-marker
                    class: primary
                    id: box-left-id
                    title: Puntos de venta
                    li_class: box-left-li
                    li_badge_class: bg-blue
                    li_input_name: box-lefts-selected-value
                    search_input_name: search-input-name-left
                    route_search: backend_orderin_search
                    route_select_item: backend_orderin_boxleft_select_item
                box_center:
                    icon: user
                    class: primary
                    id: box-center-id
                    title: Usuarios
                    li_class: box-center-li
                    li_badge_class: bg-orange-active
                    li_input_name: box-center-selected-value
                    route_select_item: backend_orderin_boxleft_select_item
#                    search_input_name: search-input-name-right
#                    route_search: backend_associative_profile_has_role_boxright_search
#                    route_select_item: backend_associative_profile_has_role_boxright_select_item
                box_right:
                    icon: newspaper-o
                    class: primary
                    id: box-right-id
                    title: Periódicos
                    li_class: box-right-li
                    li_badge_class: bg-orange-active
                    li_input_name: box-right-selected-value
#                    search_input_name: search-input-name-right
#                    route_search: backend_associative_profile_has_role_boxright_search
#                    route_select_item: backend_associative_profile_has_role_boxright_select_item
            grid:
#                icon: cube
#                box_class: primary
#                title: Gestionar productos
#                modal:
#                    title: Crear producto
                data_table:
                    route:
                    table_button:
                    table_button_header:
                        - info
                    row_call_back:
                    columns:
            form:
                type: Bundle\OrderinBundle\Form\Type\OrderinType
            repository:
                box_left:
                    service: tianos.repository.pointofsale
                    method: findAllOffsetLimit
                    arguments:
                        limit: 20
                    vars:
                        serialize_group_name: order-in-left
#                box_center:
#                    service: tianos.repository.user
#                    method: findAllOffsetLimit
#                    arguments:
#                        limit: 20
#                    vars:
#                        serialize_group_name: order-in-center
#                box_right:
#                    service: tianos.repository.user
#                    method: findAllOffsetLimit
#                    arguments:
#                        limit: 20
#                    vars:
#                        serialize_group_name: order-in-right

backend_orderin_search:
    path: /orderin-search
    methods: [POST]
    defaults:
#        _controller: tianos.profilehasrole.controller.associative:boxLeftSearchAction
        _controller: tianos.backend.controller.orderin:boxLeftSearchAction
        _tianos:
            action: left_search
#            template: OneToManyBundle:Li:box_left.html.twig
            template: OrderinBundle:OrderinBackend/Li:box_left.html.twig
            vars:
                box_left:
                    li_class: box-left-li
                    li_badge_class: bg-blue
                    li_input_name: box-lefts-selected-value
                    search_input_name: search-input-name-left
            repository:
                box_left:
                    service: tianos.repository.pointofsale
                    method: searchBoxLeft
                    arguments:
                        limit: 20
                    vars:
                        serialize_group_name: order-in-left

backend_orderin_boxleft_select_item:
    path: /orderin-select-item
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.orderin:boxLeftSelectItemAction
        _tianos:
#            template: OneToManyBundle:Li:box_right_select_item.html.twig
            template: OrderinBundle:OrderinBackend/Li:box_center_select_item.html.twig
            vars:
                box_center:
                    icon: expeditedssl
                    class: primary
                    id: box-center-id
                    title: Role
                    entity: user2
                    li_class: box-right-li
                    li_badge_class: bg-blue
                    li_input_name: box-right-selected-value
                    search_input_name: search-input-name-right
            repository:
                box_left:
                    service: tianos.repository.pointofsale
                    method: find
                    vars:
                        serialize_group_name: order-in-left-select-item
#                        serialize_group_name: one-to-many-left-profilehasrole
#                box_center:
#                    service: tianos.repository.user
#                    method: find
#                    vars:
#                        serialize_group_name: one-to-many-right












backend_orderin_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.orderin:createAction
        _tianos:
            action: create
            template: OrderinBundle:OrderinBackend/Form:form.html.twig
            entity: Bundle\OrderinBundle\Entity\Orderin
            form:
                type: Bundle\OrderinBundle\Form\Type\OrderinType
            vars:
                serialize_group_name: crud

backend_orderin_edit:
    path: /edit
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.orderin:editAction
        _tianos:
            action: edit
            template: OrderinBundle:OrderinBackend/Form:form.html.twig
            repository:
                service: tianos.repository.orderin
                method: find
                arguments: [$orderinId]
            form:
                type: Bundle\OrderinBundle\Form\Type\OrderinType
            vars:
                serialize_group_name: crud

backend_orderin_delete:
    path: /delete
    methods: [POST, DELETE]
    defaults:
        _controller: tianos.backend.controller.orderin:deleteAction
        _tianos:
            action: delete
            template: GridBundle:Template:delete.html.twig
            repository:
                service: tianos.repository.orderin
                method: find
                arguments: [$orderinId]
            vars:
#                body_css: grid-body-css

backend_orderin_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.orderin:viewAction
        _tianos:
            action: view
            template: OrderinBundle:OrderinBackend/Informative:view.html.twig
            repository:
                service: tianos.repository.orderin
                method: find
                arguments: [$orderinId]

backend_orderin_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.orderin:infoAction
        _tianos:
            action: info
            template: OrderinBundle:OrderinBackend/Informative:info.html.twig





#/var/www/html/Sylius/sylius/vendor/sylius/sylius/docs/customization/factory.rst
#
#    sylius_admin_product_create_simple:
#        path: /products/new/simple
#        methods: [GET, POST]
#        defaults:
#            _controller: sylius.controller.product:createAction
#            _sylius:
#                section: admin
#                factory:
#                    method: createDisabled # like here for example
#                template: SyliusAdminBundle:Crud:create.html.twig
#                redirect: sylius_admin_product_update
#                vars:
#                    subheader: sylius.ui.manage_your_product_catalog
#                    templates:
#                        form: SyliusAdminBundle:CRUDDUMMY:_form.html.twig
#                    route:
#                        name: sylius_admin_product_create_simple



#            template: "@SyliusAdmin/ProductVariant/generate.html.twig"
#            section: admin
#            permission: true
#            redirect:
#                route: sylius_admin_product_variant_index
#                parameters: { productId: $productId }
#            form:
#                type: Sylius\Bundle\ProductBundle\Form\Type\ProductGenerateVariantsType
#            repository:
#                method: find
#                arguments: [$productId]
#            flash: sylius.product_variant.generate

#sylius_admin_product_index:
#    path: /products/
#    methods: [GET]
#    defaults:
#        _controller: sylius.controller.product:indexAction
#        _sylius:
#            section: admin
#            permission: true
#            grid: sylius_admin_product
#            template: SyliusAdminBundle:CRUDDUMMY:index.html.twig
#            vars:
#                subheader: sylius.ui.manage_your_product_catalog
#                icon: cube
