backend_groupofusers_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.groupofusers:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            vars:
                subheader: sylius.ui.manage_your_groupofusers_catalog
                icon: cube
                body_css: grid-body-css
            grid:
                icon: users
                box_class: primary
                title: Gestionar grupo de usuarios
                modal:
                    title: Crear grupo de usuario
                data_table:
                    route:
                        info: backend_groupofusers_info
                        view: backend_groupofusers_view
                        edit: backend_groupofusers_edit
                        create: backend_groupofusers_create
                        delete: backend_groupofusers_delete
                    table_button:
                        - edit
                        - delete
                    table_button_header:
                        - create
                        - info
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
                    columns:
                        - name: '#'
                          obj: " '<span class=\"badge bg-blue\">' + obj.id + '</span>' "
                        - name: Name
                          obj: obj.name
                        - name: Creado
                          obj: obj.created_at
                          options:
                              icon: calendar
            form:
                type: Bundle\GroupofusersBundle\Form\Type\GroupofusersType
            repository:
                service: tianos.repository.groupofusers
                method: findAll
                arguments: [$groupofusersId]
                vars:
                    serialize_group_name: crud

backend_groupofusers_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.groupofusers:createAction
        _tianos:
            action: create
            template: GroupofusersBundle:BackendGroupofusers/Form:form.html.twig
            entity: Bundle\GroupofusersBundle\Entity\Groupofusers
            form:
                type: Bundle\GroupofusersBundle\Form\Type\GroupofusersType
            repository:
                vars:
                    serialize_group_name: crud

backend_groupofusers_edit:
    path: /edit
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.groupofusers:editAction
        _tianos:
            action: edit
            template: GroupofusersBundle:BackendGroupofusers/Form:form.html.twig
            form:
                type: Bundle\GroupofusersBundle\Form\Type\GroupofusersType
            repository:
                service: tianos.repository.groupofusers
                method: find
                arguments: [$groupofusersId]
                vars:
                    serialize_group_name: crud

backend_groupofusers_delete:
    path: /delete
    methods: [POST, DELETE]
    defaults:
        _controller: tianos.backend.controller.groupofusers:deleteAction
        _tianos:
            action: delete
            template: GridBundle:Template:delete.html.twig
            repository:
                service: tianos.repository.groupofusers
                method: find
                arguments: [$groupofusersId]
            vars:
#                body_css: grid-body-css

backend_groupofusers_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.groupofusers:viewAction
        _tianos:
            action: view
            template: GroupofusersBundle:BackendGroupofusers/Informative:view.html.twig
            repository:
                service: tianos.repository.groupofusers
                method: find
                arguments: [$groupofusersId]
                vars:
                    serialize_group_name: crud

backend_groupofusers_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.groupofusers:infoAction
        _tianos:
            action: info
            template: GroupofusersBundle:BackendGroupofusers/Informative:info.html.twig