snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost



#snc_redis:
#    clients:
#        default:
#            type: predis
#            alias: default
#            dsn: redis://localhost:8008
#            logging: %kernel.debug%
#        cache:
#            type: predis
#            alias: cache
#            dsn: redis://secret@localhost/1
#            options:
#                profile: 2.2
#                connection_timeout: 10
#                read_write_timeout: 30
#        session:
#            type: predis
#            alias: session
#            dsn: redis://localhost/2
#        cluster:
#            type: predis
#            alias: cluster
#            dsn:
#                - redis://localhost/3?weight=10
#                - redis://localhost/4?weight=5
#                - redis://localhost/5?weight=1