Bundle\UserBundle\Entity\Friends:
    type: entity
    table: friends
    repositoryClass: Bundle\UserBundle\Doctrine\ORM\FriendsRepository
    indexes:
        fk_friends_user1_idx:
            columns:
                - user_id
        fk_friends_user2_idx:
            columns:
                - friend_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        isActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: is_active
    manyToOne:
        user:
            targetEntity: Bundle\UserBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        friend:
            targetEntity: Bundle\UserBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                friend_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
