#http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/yaml-mapping.html

Bundle\UserBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: Bundle\UserBundle\Doctrine\ORM\UserRepository
    indexes:
        FK_8D93D649CCFA12B8:
            columns:
                - profile_id
        fk_user_client1_idx:
            columns:
                - client_id
    uniqueConstraints:
        email_UNIQUE:
            columns:
                - email
        username_UNIQUE:
            columns:
                - username
#        dni_UNIQUE:
#            columns:
#                - dni
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
#        username:
#            type: string
#            nullable: false
#            length: 45
#            options:
#                fixed: false
        slug:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        deviceCode:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: device_code
#        password:
#            type: string
#            nullable: true
#            length: 100
#            options:
#                fixed: false
#        salt:
#            type: string
#            nullable: true
#            length: 45
#            options:
#                fixed: false
#        dni:
#            type: string
#            nullable: true
#            length: 8
#            options:
#                fixed: false
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        lastName:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: last_name
        dob:
            type: date
            nullable: true
        address:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
#        email:
#            type: string
#            nullable: false
#            length: 255
#            options:
#                fixed: false
        phone:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        userCreate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        userUpdate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_update
        lastAccess:
            type: datetime
            nullable: true
            column: last_access
    manyToOne:
        profile:
            targetEntity: Bundle\ProfileBundle\Entity\Profile
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                profile_id:
                    referencedColumnName: id
            orphanRemoval: false
        client:
            targetEntity: Bundle\ClientBundle\Entity\Client
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                client_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        groupOfUsers:
            targetEntity: Bundle\GroupofusersBundle\Entity\Groupofusers
            cascade: {  }
            fetch: LAZY
            mappedBy: user
            inversedBy: null
            joinTable: null
            orderBy: null
        pointOfSale:
            targetEntity: Bundle\PointofsaleBundle\Entity\Pointofsale
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: user
            joinTable:
                name: user_has_point_of_sale
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: point_of_sale_id
                        referencedColumnName: id
            orderBy: null
        pointOfSale2:
            targetEntity: Bundle\PointofsaleBundle\Entity\Pointofsale
            cascade: {  }
            fetch: LAZY
            mappedBy: user
            inversedBy: null
            joinTable: null
            orderBy: null
        route:
            targetEntity: Bundle\RouteBundle\Entity\Route
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: user
            joinTable:
                name: user_has_route
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: route_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }