services:
    - { tianos.profilehasrole.controller.associative: { class: Bundle\AssociativeBundle\ControllerProfileHasRoleController, arguments: [Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface], tags: [{ name: tianos.profilehasrole.controller.associative, alias: tianos.profilehasrole.controller.associative }] } }
