services:

    tianos.profilehasrole.controller.associative:
        class: Bundle\AssociativeBundle\Controller\ProfileHasRoleController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.profilehasrole.controller.associative, alias: tianos.profilehasrole.controller.associative }

#    tianos.repository.profile:
#        class: Dummy
#        factory: ['@doctrine.orm.entity_manager', getRepository]
#        arguments: [ Bundle\ProfileBundle\Entity\Profile ]



#    tianos.controller.grid:
#        class: Bundle\GridBundle\Controller\GridController
#        arguments: [ Bundle\GridBundle\Controller\RequestConfigurationFactoryInterface ]
#        tags:
#            - { name: tianos.controller.grid, alias: tianos.controller.grid }