backend_order_report_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.report.controller.order:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            vars:
                subheader: sylius.ui.manage_your_client_catalog
                icon: cube
                body_css: grid-body-css
            grid:
                icon: bar-chart
                box_class: primary
                title: 'Puntos de venta: pedidos y devoluciones de periódicos'
                modal:
                    title: Crear cliente
                data_table:
                    route:
                        info: backend_order_report_info
                    table_button:
#                        - edit
#                        - delete
                    table_button_header:
#                        - create
                        - info
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
                    columns:
                        - name: '#'
                          obj: " '<span class=\"badge bg-blue\">' + obj.id + '</span>' "
                        - name: Punto de venta
                          obj: " '<small class=\"label bg-blue\">' + obj.point_of_sale.id + '</small> ' + obj.point_of_sale.name_box"
                          options:
                              icon: map-marker
                        - name: Canillita
                          obj: obj.user.name_box
                          options:
                              icon: user
                        - name: Producto
                          obj: " '<small class=\"label bg-blue\">' + obj.product.id + '</small> ' + obj.product.name_box "
                          options:
                              icon: cube
                        - name: Cantidad
                          obj: " '<span class=\"badge bg-green\">' + obj.quantity + '</span>' "
                          options:
                              icon: history
                        - name: Tipo
                          obj: obj.type
                          options:
                              icon: sign-out
                              property: " return (obj.type == 'IN') ? '<small class=\"label bg-yellow\" style=\"font-size:12.5px\">Devolución</small> ' : '<small class=\"label bg-green\" style=\"font-size:12.5px\">Pedido</small> ' "
                        - name: Fecha
                          obj: obj.order_date
                          options:
                              icon: calendar
            form:
                type: Bundle\OrderBundle\Form\Type\OrderType
            repository:
                service: tianos.repository.order
                method: findAll
                arguments: [$clientId]
                vars:
                    serialize_group_name: order-report

backend_order_report_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.report.controller.order:infoAction
        _tianos:
            action: info
            template: OrderBundle:OrderReportBackend/Informative:info.html.twig