frontend_orderin_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.frontend.controller.order:indexAction
        _tianos:
            section: admin
            permission: true
            grid: sylius_admin_orderin
            template: OrderBundle:Orderin:index.html.twig
            vars:
                subheader: sylius.ui.manage_your_orderin_catalog
                icon: cube
            form:
                type: Bundle\OrderBundle\Form\Type\OrderinType
            repository:
                service: tianos.repository.order
                method: findAll
                arguments: [$orderinId]
