backend_google_drive_vote_like_dislike:
    path: /like-dislike
    methods: [PUT, POST]
    defaults:
        _controller: tianos.google.drive.vote.controller.google:voteAction
        _tianos:
            action: edit
            template: GoogleBundle:GoogleDriveFileGrid/Form:form.html.twig
            form:
                type: Bundle\GoogleBundle\Form\Type\GoogleType
            repository:
                service: tianos.repository.google.drive.vote
                method: find
                arguments: [$clientId]
                vars:
                    serialize_group_name: google-drive-file-vote
