backend_areaacademica_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.areaacademica:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            vars:
                subheader: sylius.ui.manage_your_areaacademica_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
#            grid: sylius_admin_product
            grid:
                icon: bookmark
                box_class: primary
                title: Gestionar Áreas académicas
                data_table:
                    route:
                        info: backend_areaacademica_info
                        view: backend_areaacademica_view
                        edit: backend_areaacademica_edit
                        create: backend_areaacademica_create
                        delete: backend_areaacademica_delete
                    table_button:
                        - edit
                        - delete
                    table_button_header:
                        - create
                        - info
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
                    columns:
                        - name: '#'
                          obj: " '<span class=\"badge bg-blue\">' + obj.id + '</span>' "
                        - name: Name
                          obj: obj.name
                        - name: Creado
                          obj: obj.created_at
                          options:
                              icon: calendar
            form:
                type: Bundle\AreaacademicaBundle\Form\Type\AreaacademicaType
            repository:
                service: tianos.repository.areaacademica
                method: findAll
                arguments: [$areaacademicaId]
                vars:
                    serialize_group_name: crud

backend_areaacademica_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.areaacademica:createAction
        _tianos:
            action: create
            template: AreaacademicaBundle:BackendAreaacademica/Form:form.html.twig
            entity: Bundle\AreaacademicaBundle\Entity\Areaacademica
            form:
                type: Bundle\AreaacademicaBundle\Form\Type\AreaacademicaType
            repository:
                vars:
                    serialize_group_name: crud

backend_areaacademica_edit:
    path: /edit
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.areaacademica:editAction
        _tianos:
            action: edit
            template: AreaacademicaBundle:BackendAreaacademica/Form:form.html.twig
            form:
                type: Bundle\AreaacademicaBundle\Form\Type\AreaacademicaType
            repository:
                service: tianos.repository.areaacademica
                method: find
                arguments: [$areaacademicaId]
                vars:
                    serialize_group_name: crud

backend_areaacademica_delete:
    path: /delete
    methods: [POST, DELETE]
    defaults:
        _controller: tianos.backend.controller.areaacademica:deleteAction
        _tianos:
            action: delete
            template: GridBundle:Template:delete.html.twig
            repository:
                service: tianos.repository.areaacademica
                method: find
                arguments: [$areaacademicaId]
            vars:
#                body_css: grid-body-css

backend_areaacademica_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.areaacademica:viewAction
        _tianos:
            action: view
            template: AreaacademicaBundle:BackendAreaacademica/Informative:view.html.twig
            repository:
                service: tianos.repository.areaacademica
                method: find
                arguments: [$areaacademicaId]
                vars:
                    serialize_group_name: crud

backend_areaacademica_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.areaacademica:infoAction
        _tianos:
            action: info
            template: AreaacademicaBundle:BackendAreaacademica/Informative:info.html.twig





#/var/www/html/Sylius/sylius/vendor/sylius/sylius/docs/customization/factory.rst
#
#    sylius_admin_product_create_simple:
#        path: /products/new/simple
#        methods: [GET, POST]
#        defaults:
#            _controller: sylius.controller.product:createAction
#            _sylius:
#                section: admin
#                factory:
#                    method: createDisabled # like here for example
#                template: SyliusAdminBundle:Crud:create.html.twig
#                redirect: sylius_admin_product_update
#                vars:
#                    subheader: sylius.ui.manage_your_product_catalog
#                    templates:
#                        form: SyliusAdminBundle:CRUDDUMMY:_form.html.twig
#                    route:
#                        name: sylius_admin_product_create_simple



#            template: "@SyliusAdmin/ProductVariant/generate.html.twig"
#            section: admin
#            permission: true
#            redirect:
#                route: sylius_admin_product_variant_index
#                parameters: { productId: $productId }
#            form:
#                type: Sylius\Bundle\ProductBundle\Form\Type\ProductGenerateVariantsType
#            repository:
#                method: find
#                arguments: [$productId]
#            flash: sylius.product_variant.generate

#sylius_admin_product_index:
#    path: /products/
#    methods: [GET]
#    defaults:
#        _controller: sylius.controller.product:indexAction
#        _sylius:
#            section: admin
#            permission: true
#            grid: sylius_admin_product
#            template: SyliusAdminBundle:CRUDDUMMY:index.html.twig
#            vars:
#                subheader: sylius.ui.manage_your_product_catalog
#                icon: cube
