backend_visit_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.visit:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            vars:
                subheader: sylius.ui.manage_your_visit_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
#            grid: sylius_admin_product
            grid:
                icon: cube
                box_class: primary
                title: Gestionar visitas
                data_table:
                    route:
                        info: backend_visit_info
                        view: backend_visit_view
#                        edit: backend_visit_edit
#                        create: backend_visit_create
#                        delete: backend_visit_delete
                    table_button:
#                        - edit
#                        - delete
                    table_button_header:
#                        - create
                        - info
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
                    columns:
                        - name: '#'
                          obj: " '<span class=\"badge bg-blue\">' + obj.id + '</span>' "
                        - name: Usuario
                          obj: " obj.user.name + ' ' + obj.user.last_name "
                        - name: Punto de venta
                          obj: obj.point_of_sale.name
                        - name: Inicio de visita
                          obj: " '<small class=\"label bg-green\" style=\"font-size:13px\">' + obj.visit_start + '</small>' "
                        - name: Fin de visita
                          obj: " '<small class=\"label bg-orange\" style=\"font-size:13px\">' + obj.visit_end + '</small>' "
                        - name: Uuid
                          obj: obj.uuid
                          options:
                              icon: calendar
#                        - name: Creado
#                          obj: obj.created_at
            form:
                type: Bundle\VisitBundle\Form\Type\VisitType
            repository:
                service: tianos.repository.visit
                method: findAll
                arguments: [$visitId]

backend_visit_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.visit:viewAction
        _tianos:
            action: view
            template: VisitBundle:VisitBackend/Informative:view.html.twig
            repository:
                service: tianos.repository.visit
                method: find
                arguments: [$visitId]

backend_visit_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.visit:infoAction
        _tianos:
            action: info
            template: VisitBundle:VisitBackend/Informative:info.html.twig

#backend_visit_create:
#    path: /create
#    methods: [POST]
#    defaults:
#        _controller: tianos.backend.controller.visit:createAction
#        _tianos:
#            action: create
#            template: VisitBundle:VisitBackend/Form:form.html.twig
#            entity: Bundle\VisitBundle\Entity\Visit
#            form:
#                type: Bundle\VisitBundle\Form\Type\VisitType
#            vars:
#                serialize_group_name: crud