frontend_client_bundle_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.frontend.controller.client:indexAction
        _tianos:
            section: admin
            permission: true
            grid: sylius_admin_client
            template: ClientBundle:Client:index.html.twig
            vars:
                subheader: sylius.ui.manage_your_client_catalog
                icon: cube
            form:
                type: Bundle\ClientBundle\Form\Type\ClientType
            repository:
                service: tianos.repository.client
                method: findAll
                arguments: [$clientId]
