Bundle\TicketBundle\Entity\Ticket:
    type: entity
#    type: mappedSuperclass
#    mappedSuperclass: Component\CRUDDUMMY\Model\CRUDDUMMY
    table: ticket
    repositoryClass: Bundle\TicketBundle\Doctrine\ORM\TicketRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        dateTicket:
            type: datetime
            nullable: false
            column: date_ticket
        slug:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
#        image:
#            type: string
#            nullable: true
#            length: 45
#            options:
#                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
#            gedmo:
#                timestampable:
#                    on: create
        userCreate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        userUpdate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_update
        isActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: is_active
    manyToOne:
        client:
            targetEntity: Bundle\UserBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                client_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        employee:
            targetEntity: Bundle\UserBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: ticket
            joinTable:
                name: ticket_has_employee
                joinColumns:
                    -
                        name: ticket_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
#    lifecycleCallbacks:
#        prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]
#        postPersist: [ doStuffOnPostPersist ]
