services:

    tianos.listener.doctrine.calendar:
        class: Bundle\CalendarBundle\EventListener\DoctrineListenerService
        arguments: ["@security.token_storage"]
        tags:
          - { name: doctrine.event_listener, event: postUpdate }
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: postLoad }
          - { name: doctrine.event_listener, event: postRemove }

    tianos.api.controller.calendar:
        class: Bundle\CalendarBundle\Controller\ApiController
        arguments: [ Bundle\GridBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.api.controller.calendar, alias: tianos.api.controller.calendar }

    tianos.backend.controller.calendar:
        class: Bundle\CalendarBundle\Controller\BackendController
        arguments: [ Bundle\GridBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.backend.controller.calendar, alias: tianos.backend.controller.calendar }

    tianos.frontend.controller.calendar:
        class: Bundle\CalendarBundle\Controller\FrontendController
        arguments: [ Bundle\GridBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.frontend.controller.calendar, alias: tianos.frontend.controller.calendar }

    tianos.repository.calendar:
        class: Dummy
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Bundle\CalendarBundle\Entity\Calendar ]



#    tianos.controller.grid:
#        class: Bundle\GridBundle\Controller\GridController
#        arguments: [ Bundle\GridBundle\Controller\RequestConfigurationFactoryInterface ]
#        tags:
#            - { name: tianos.controller.grid, alias: tianos.controller.grid }