#http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/yaml-mapping.html

Bundle\FacultadBundle\Entity\Facultad:
    type: entity
#    type: mappedSuperclass
#    mappedSuperclass: Component\CRUDDUMMY\Model\CRUDDUMMY
    table: facultad
    repositoryClass: Bundle\FacultadBundle\Doctrine\ORM\FacultadRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        slug:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
#        image:
#            type: string
#            nullable: true
#            length: 45
#            options:
#                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
#            gedmo:
#                timestampable:
#                    on: create
        userCreate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        userUpdate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_update
        isActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: is_active
    manyToMany:
        areaacademica:
            targetEntity: Bundle\AreaacademicaBundle\Entity\Areaacademica
            cascade: {  }
            fetch: LAZY
            mappedBy: facultad
            inversedBy: null
            joinTable: null
            orderBy: null
        escuela:
            targetEntity: Bundle\EscuelaBundle\Entity\Escuela
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: facultad
            joinTable:
                name: facultad_has_escuela
                joinColumns:
                    -
                        name: facultad_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: escuela_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
#    lifecycleCallbacks:
#        prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]
#        postPersist: [ doStuffOnPostPersist ]
