#http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/yaml-mapping.html

Bundle\PdvhasproductBundle\Entity\Pdvhasproduct:
    type: entity
#    type: mappedSuperclass
#    mappedSuperclass: Component\CRUDDUMMY\Model\CRUDDUMMY
    table: pdv_has_product
    repositoryClass: Bundle\PdvhasproductBundle\Doctrine\ORM\PdvhasproductRepository
    indexes:
        fk_pdv_has_product_product1_idx:
            columns:
                - product_id
        fk_pdv_has_product_point_of_sale1_idx:
            columns:
                - point_of_sale_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
        slug:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
        uuid:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        quantity:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: quantity
        createdAt:
            type: datetime
            nullable: false
            column: created_at
#            gedmo:
#                timestampable:
#                    on: create
        userCreate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        userUpdate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_update
        isActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: is_active
    manyToOne:
        pointOfSale:
            targetEntity: Bundle\PointofsaleBundle\Entity\Pointofsale
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                point_of_sale_id:
                    referencedColumnName: id
            orphanRemoval: false
        product:
            targetEntity: Bundle\ProductBundle\Entity\Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Bundle\UserBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
