backend_associative_route_has_pointofsale_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.routehaspointofsale.controller.associative:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: OneToManyBundle::index.html.twig
            vars:
                subheader: sylius.ui.manage_your_route_catalog
                icon: cube
                body_css: one-to-many-body-css
            one_to_many:
                box:
                    icon: exchange
                    class: primary
                    form_name: main-form
                    title: Ruta<i class="fa fa-fw fa-angle-double-right"></i>tiene<i class="fa fa-fw fa-angle-double-right"></i>Puntos de venta
                    route_info: backend_associative_route_has_pointofsale_info
                box_left:
                    icon: road
                    class: primary
                    id: box-left-id
                    title: Rutas
                    li_class: box-left-li
                    li_badge_class: bg-blue
                    li_input_name: box-lefts-selected-value
                    search_input_name: search-input-name-left
                    route_search: backend_associative_route_has_pointofsale_boxleft_search
                    route_select_item: backend_associative_route_has_pointofsale_boxleft_select_item
                box_right:
                    icon: map-marker
                    class: primary
                    id: box-right-id
                    title: Puntos de venta
                    li_class: box-right-li
                    li_badge_class: bg-orange-active
                    li_input_name: box-right-selected-value
                    search_input_name: search-input-name-right
                    route_search: backend_associative_route_has_pointofsale_boxright_search
                    route_select_item: backend_associative_route_has_pointofsale_boxright_select_item
            form:
                type: Bundle\RouteBundle\Form\Type\RouteType
            repository:
                box_left:
                    service: tianos.repository.route
                    method: findAllOffsetLimit
                    arguments:
                        limit: 20
                    vars:
                        serialize_group_name: one-to-many-left
                box_right:
                    service: tianos.repository.pointofsale
                    method: findAllOffsetLimit
                    arguments:
                        limit: 20
                    vars:
                        serialize_group_name: one-to-many-right

backend_associative_route_has_pointofsale_boxleft_search:
    path: /boxleft-search
    methods: [POST]
    defaults:
        _controller: tianos.routehaspointofsale.controller.associative:boxLeftSearchAction
        _tianos:
            action: left_search
            template: OneToManyBundle:Li:box_left.html.twig
            one_to_many:
                box_left:
                    li_class: box-left-li
                    li_badge_class: bg-blue
                    li_input_name: box-lefts-selected-value
                    search_input_name: search-input-name-left
            repository:
                box_left:
                    service: tianos.repository.route
                    method: searchBoxLeft
                    arguments:
                        limit: 20
                    vars:
                        serialize_group_name: one-to-many-left

backend_associative_route_has_pointofsale_boxright_search:
    path: /boxright-search
    methods: [POST]
    defaults:
        _controller: tianos.routehaspointofsale.controller.associative:boxRightSearchAction
        _tianos:
            action: right_search
            template: OneToManyBundle:Li:box_right_search.html.twig
            one_to_many:
                box_right:
                    li_class: box-right-li
                    li_badge_class: bg-blue
                    li_input_name: box-lefts-selected-value
                    search_input_name: search-input-name-left
            repository:
                box_left:
                    service: tianos.repository.route
                    method: oneToManyLeft
                    arguments:
                        limit: 20
                    vars:
                        serialize_group_name: one-to-many-search
                box_right:
                    service: tianos.repository.pointofsale
                    method: searchBoxRight
                    arguments:
                        limit: 20
                    vars:
                        serialize_group_name: one-to-many-right

backend_associative_route_has_pointofsale_boxright_select_item:
    path: /boxright-select-item
    methods: [POST]
    defaults:
        _controller: tianos.routehaspointofsale.controller.associative:boxRightSelectItemAction
        _tianos:
            repository:
                box_left:
                    service: tianos.repository.route
                    method: find
                    add_entity: addPointOfSale
                    remove_entity: removePointOfSale
                    method_delete_associative: deleteAssociativeTableById
                box_right:
                    service: tianos.repository.pointofsale
                    method: find

backend_associative_route_has_pointofsale_boxleft_select_item:
    path: /boxleft-select-item
    methods: [POST]
    defaults:
        _controller: tianos.routehaspointofsale.controller.associative:boxLeftSelectItemAction
        _tianos:
            template: OneToManyBundle:Li:box_right_select_item.html.twig
            one_to_many:
                box_right:
                    icon: expeditedssl
                    class: primary
                    id: box-right-id
                    title: Pointofsale
                    entity: point_of_sale
                    li_class: box-right-li
                    li_badge_class: bg-orange-active
                    li_input_name: box-right-selected-value
                    search_input_name: search-input-name-right
            repository:
                box_left:
                    service: tianos.repository.route
                    method: find
                    vars:
                        serialize_group_name: one-to-many-left
                box_right:
                    service: tianos.repository.pointofsale
                    method: find
                    vars:
                        serialize_group_name: one-to-many-right

backend_associative_route_has_pointofsale_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.routehaspointofsale.controller.associative:infoAction
        _tianos:
            action: info
            template: AssociativeBundle:RouteHasPointofsale/Informative:info.html.twig











#backend_profile_has_role_edit:
#    path: /edit
#    methods: [PUT, POST]
#    defaults:
#        _controller: tianos.profilehasrole.controller.profile:editAction
#        _tianos:
#            action: edit
#            template: ProfileBundle:ProfileBackend/Form:form.html.twig
#            repository:
#                service: tianos.repository.profile
#                method: find
#                arguments: [$profileId]
#            form:
#                type: Bundle\ProfileBundle\Form\Type\ProfileType
#            vars:
#                serialize_group_name: crud
#
#backend_profile_has_role_delete:
#    path: /delete
#    methods: [POST, DELETE]
#    defaults:
#        _controller: tianos.profilehasrole.controller.profile:deleteAction
#        _tianos:
#            action: delete
#            template: GridBundle:Template:delete.html.twig
#            repository:
#                service: tianos.repository.profile
#                method: find
#                arguments: [$profileId]
#            vars:
##                body_css: grid-body-css
#
#backend_profile_has_role_view:
#    path: /view
#    methods: [POST]
#    defaults:
#        _controller: tianos.profilehasrole.controller.profile:viewAction
#        _tianos:
#            action: view
#            template: ProfileBundle:ProfileBackend/Informative:view.html.twig
#            repository:
#                service: tianos.repository.profile
#                method: find
#                arguments: [$profileId]


