api_default:
    resource: '@ApiBundle/Resources/config/routing/default.yml'
    prefix: /

api_category:
    resource: '@CategoryBundle/Resources/config/routing/api.yml'
    prefix: /category

api_user:
    resource: '@UserBundle/Resources/config/routing/api.yml'
    prefix: /user

api_visit:
    resource: '@VisitBundle/Resources/config/routing/api.yml'
    prefix: /visit