#http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/yaml-mapping.html

Bundle\BookingBundle\Entity\Booking:
    type: entity
#    type: mappedSuperclass
#    mappedSuperclass: Component\CRUDDUMMY\Model\CRUDDUMMY
    table: booking
    repositoryClass: Bundle\BookingBundle\Doctrine\ORM\BookingRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        slug:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
        dateBook:
            type: date
            nullable: false
            column: date_book
        timeInBook:
            type: time
            nullable: false
            column: time_in_book
        timeOutBook:
            type: time
            nullable: false
            column: time_out_book
        createdAt:
            type: datetime
            nullable: false
            column: created_at
#            gedmo:
#                timestampable:
#                    on: create
        userCreate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        userUpdate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_update
        isActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: is_active
#        image:
#            type: string
#            nullable: true
#            length: 45
#            options:
#                fixed: false
    manyToOne:
        client:
            targetEntity: Bundle\UserBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                client_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
#    lifecycleCallbacks:
#        prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]
#        postPersist: [ doStuffOnPostPersist ]
