Bundle\GoogleBundle\Entity\GoogleDriveFileCount:
    type: entity
    table: google_drive_file_count
    repositoryClass: Bundle\GoogleBundle\Doctrine\ORM\GoogleDriveFileCountRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fileId:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: file_id
        countShare:
            type: integer
            nullable: true
            length: 11
            options:
                fixed: false
            column: count_share
        countView:
            type: integer
            nullable: true
            length: 11
            options:
                fixed: false
            column: count_view
    lifecycleCallbacks: {  }