Bundle\GoogleBundle\Entity\GoogleDriveFileVote:
    type: entity
    table: google_drive_file_vote
    repositoryClass: Bundle\GoogleBundle\Doctrine\ORM\GoogleDriveFileVoteRepository
    indexes:
        fk_google_drive_file_like_google_drive_file1_idx:
            columns:
                - google_drive_file_id
        fk_google_drive_file_like_user1_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vote:
            type: boolean
            nullable: true
            options:
                default: '0'
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        isActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: is_active
    manyToOne:
        user:
            targetEntity: Bundle\UserBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        googleDriveFile:
            targetEntity: Bundle\GoogleBundle\Entity\GoogleDriveFile
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                google_drive_file_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
