api_product_index:
    path: /
    methods: [POST]
    defaults:
        _controller: tianos.api.controller.product:indexAction
        _tianos:
            section: admin
            permission: true
            grid: sylius_admin_product
            template: ProductBundle:Product:index.html.twig
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                icon: cube
                serialize_group_name: api
            form:
                type: Bundle\ProductBundle\Form\Type\ProductType
            repository:
                service: tianos.repository.product
                method: findAll
                arguments: [$productId]

