backend_product_bundle_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.product:indexAction
        _tianos:
            section: admin
            permission: true
            template: GridBundle:Grid:index.html.twig
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                icon: cube
#            grid: sylius_admin_product
            grid:
                icon: cube
                box_class: primary
                table_name: table-grid
                title: Gestionar productos
                table_tr_class: row-tr-class
            form:
                type: Bundle\ProductBundle\Form\Type\ProductType
            repository:
                service: tianos.repository.product
                method: findAll
                arguments: [$productId]


#/var/www/html/Sylius/sylius/vendor/sylius/sylius/docs/customization/factory.rst
#
#    sylius_admin_product_create_simple:
#        path: /products/new/simple
#        methods: [GET, POST]
#        defaults:
#            _controller: sylius.controller.product:createAction
#            _sylius:
#                section: admin
#                factory:
#                    method: createDisabled # like here for example
#                template: SyliusAdminBundle:Crud:create.html.twig
#                redirect: sylius_admin_product_update
#                vars:
#                    subheader: sylius.ui.manage_your_product_catalog
#                    templates:
#                        form: SyliusAdminBundle:Product:_form.html.twig
#                    route:
#                        name: sylius_admin_product_create_simple



#            template: "@SyliusAdmin/ProductVariant/generate.html.twig"
#            section: admin
#            permission: true
#            redirect:
#                route: sylius_admin_product_variant_index
#                parameters: { productId: $productId }
#            form:
#                type: Sylius\Bundle\ProductBundle\Form\Type\ProductGenerateVariantsType
#            repository:
#                method: find
#                arguments: [$productId]
#            flash: sylius.product_variant.generate



#
#sylius_admin_product_index:
#    path: /products/
#    methods: [GET]
#    defaults:
#        _controller: sylius.controller.product:indexAction
#        _sylius:
#            section: admin
#            permission: true
#            grid: sylius_admin_product
#            template: SyliusAdminBundle:Product:index.html.twig
#            vars:
#                subheader: sylius.ui.manage_your_product_catalog
#                icon: cube

#backend_product_index:
#    path: /
#    defaults: { _controller: ProductBundle:Product:index }
#    methods: [GET]

#backend_product_create:
#    path: /create
#    defaults: { _controller: 'BackendBundle:Product:create' }
#    methods: [POST]
#
#backend_product_edit:
#    path: /edit
#    defaults: { _controller: 'BackendBundle:Product:edit' }
#    methods: [POST, PUT]
#
#backend_product_delete:
#    path: /delete
#    defaults: { _controller: 'BackendBundle:Product:delete' }
#    methods: [POST, DELETE]
#
#backend_product_view:
#    path: /view
#    defaults: { _controller: 'BackendBundle:Product:view' }
#    methods: [POST]
#
#backend_product_info:
#    path: /info
#    defaults: { _controller: 'BackendBundle:Product:info' }
#    methods: [POST]
